### ISSUE TITLE
Version 1.3 doesn't change size horizontally on Google Now Launcher

### ISSUE THREAD

**Issue by cesarcardoso** [tommasoberlose/another-widget#10]
On version 1.3, Another Widget doesn't change size horizontally on Google Now Launcher. Vertically all works as intended. It doesn't happen on Nova Launcher.

![screenshot_20171106-151435](https://user-images.githubusercontent.com/4887578/32459368-9983e7f6-c316-11e7-8b61-4e449c681268.png)

**Comment by tommasoberlose** [comment]
Hopefully fixed in version 2.0.1.
