### ISSUE TITLE
NL: the month starts with a capital letter, but it shouldn't.

### ISSUE THREAD

**Issue by JordyEGNL** [tommasoberlose/another-widget#101]
**Describe the bug**
Month starts with a capital letter but it shouldn't.

**To Reproduce**
1. Set phone's language to Dutch
2. Refresh the weather
3. Look at date
4. Month starts with a capital letter but it shouldn't.

**Expected behavior**
"11 mei" instead of "11 Mei"

**Screenshots**
![Screenshot_20200511_195413](https://user-images.githubusercontent.com/65036298/81594723-a71eb480-93c1-11ea-8c4e-b12450ca675a.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei ANE-LX1
 - OS Version: Android 9
 - App Version (that you can find inside the advanced settings) 2.0.8 (87)

**Comment by tommasoberlose** [comment]
Fixed
