### ISSUE TITLE
"Glance" feature not working

### ISSUE THREAD

**Issue by FireDrop6000** [tommasoberlose/another-widget#103]
With the brand new update of Another Widget there came many new features among which the feature "glance" was quite cool. However though I turned on "glance" and gave the necessary permissions required neither song info was shown nor battery level. My device is Asus Zenfone Max running Android 6. I don't know if that makes a problem or not but the "glance" feature is really not working as it should have. I removed Another Widget from battery optimisation and Auto Start Manager but the "glance" seems to be the only thing that's not working. I will be grateful sir if you please look into the problem.

**Comment by tommasoberlose** [comment]
The glance info shows up only when you have no events.

**Comment by banksio** [comment]
For me, song info works but battery level does not. I have adjusted the message priorities in the app.

**Comment by FireDrop6000** [comment]
Even if I don't have any current event "glance" fails to show up. Well I tried this. I played a song ,the widget did not show current playing song. Now I opened the app(I did not remove the widget ) and refreshed the widget,the song showed up. I closed the song and played it again. Song did not show up. Believe me I tried all this yesterday the glance did not work even though I did not have any ongoing event. I also faced this sometimes weather does not update automatically,I need to refresh the widget to update weather even though I set weather update at 30 minutes and saw all of these yesterday. @tommasoberlose what should I do??

**Comment by tommasoberlose** [comment]
> Even if I don't have any current event "glance" fails to show up. Well I tried this. I played a song ,the widget did not show current playing song. Now I opened the app(I did not remove the widget ) and refreshed the widget,the song showed up. I closed the song and played it again. Song did not show up. Believe me I tried all this yesterday the glance did not work even though I did not have any ongoing event. I also faced this sometimes weather does not update automatically,I need to refresh the widget to update weather even though I set weather update at 30 minutes and saw all of these yesterday. @tommasoberlose what should I do??

The glance features require a few conditions to show up:
- you don't have any events visible (you could try to disable the events section)
- The current song uses the notifications to show the current title of the song, so you need to grant the app the permission to access the notifications. 
- Low battery level shows up when the battery level is very low, but I disabled this feature in the new releases because it wasn't reliable
- Daily steps shows up when you finish walking or running. It will disappear in 5 minutes

Doesn't even the custom notes show up?

**Comment by bassmadrigal** [comment]
Is it possible to always have your daily steps show up?

**Comment by tjsuominen** [comment]
Perhaps if that (permanent) is an option, but I'd like to see still my music playing etc other Glances. So this 5 min is fine with me.

**Comment by tommasoberlose** [comment]
> Is it possible to always have your daily steps show up?

That's not possible, because I can't update the widget with a high frequency to ensure the updated daily steps count every time you look at the widget. I can only react to the end of an activity, like walking or running.
