### ISSUE TITLE
Bug? Event timer 1hr earlier

### ISSUE THREAD

**Issue by leoyinjou** [tommasoberlose/another-widget#104]
**Describe the bug**
For all calendar events the event countdown is 1hr less and the event seems to start 1hr earlier than scheduled in calendars.

**To Reproduce**
Enable calendar event function.
Look at the widget's event details.

**Expected behavior**
The countdown should count down to the scheduled time of event, not an hour earlier.

**Screenshots**
![Screenshot_20200512-170245__01](https://user-images.githubusercontent.com/64910443/81665790-bfe7a280-9473-11ea-8014-86bd646d969c.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS Version: Android 10
 - App Version: v2.0.8 (87)

**Comment by tommasoberlose** [comment]
I can't update the widget every minute so I have to remove the "in 1h" a long time before the event. Otherwise you will see the "Meeting in 1h" when the meeting is in 5 minutes for example.

I can change the text to "soon" when there's less than one hour left to the event

**Comment by leoyinjou** [comment]
Yes, i understand, that makes a lot of sense. But also when the event is actually an hour away the notification seems to lose its meaning. Your suggested fix seems like a very sensible one, looking forward to the improvement! Thank you.

**Comment by tommasoberlose** [comment]
I've added an "update frequency" option in the last update that I'll push to the play store asap.
