### ISSUE TITLE
Glance Data Source Priority

### ISSUE THREAD

**Issue by lohmobius** [tommasoberlose/another-widget#105]
I am unable to change the sort order of the Data Source Priority under glance.
If I tap out or hit back it always ends up resetting the order to default.
Pixel 3 XL, beta channel.

**Comment by tommasoberlose** [comment]
Hey, are you able to drag and drop the elements in the sort menu?

**Comment by lohmobius** [comment]
I was able to in the previous build (when I posted this).  As of now I can drag/drop and they stay in place.  I don't have any glance things to show as of right now, but it seems to work correctly now.
