### ISSUE TITLE
Version 2.0.8 keeps crashing on startup

### ISSUE THREAD

**Issue by pratnala** [tommasoberlose/another-widget#106]
**Describe the bug**
The latest version, 2.0.8 crashes immediately on opening the app

**To Reproduce**
1. Open 'Another Widget' from your app drawer
2. Crash

**Expected behavior**
The app should open to allow me to configure

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 Ultra
 - OS Version: Android 10
 - App Version 2.0.8

**Additional context**

**Comment by mnurolcay** [comment]
Same here, Android 10 Oxygen Os

**Comment by sequelae75** [comment]
Same here. OnePlus 6 Oxygen Os - Android 10

**Comment by lohmobius** [comment]
Same, Android 10, Pixel 3 XL

**Comment by dvvmvp** [comment]
- Same bug on Xiaomi Mi 9T Pro (Android 10, MIUI 11.0.6).

**Comment by dvvmvp** [comment]
- Same bug on Xiaomi Mi 9T Pro (MIUI 11.0.6 on top of Android 10).

**Comment by leoyinjou** [comment]
Same.
OnePlus 7 Pro
OxygenOS Android 10

**Comment by lucasgasparotto** [comment]
I just update and the widget broke. I cannot even open it.
![Screenshot_20200512-213442](https://user-images.githubusercontent.com/3969536/81758586-a147d280-9498-11ea-812c-6c806e58000c.jpg)

**Comment by diyachan** [comment]
Same here: Galaxy M20 running OneUI 2.0 (Android 10). Logcat attached
[widget_crash.txt](https://github.com/tommasoberlose/another-widget/files/4619463/widget_crash.txt)

**Comment by pratnala** [comment]
Fixed with latest update
