### ISSUE TITLE
Notification Access

### ISSUE THREAD

**Issue by amfakh** [tommasoberlose/another-widget#108]
**Is your feature request related to a problem? Please describe.**
I've been accustomed to see the notification in Glance like Lawnchair did

**Describe the solution you'd like**
Add the notification access to read the notification from some major chatting app

**Describe alternatives you've considered**
An implementation of whitelist app would be great in the future

**Additional context**
This is the example
![Screenshot_20200513-130128_Lawnchair](https://user-images.githubusercontent.com/8016957/81776898-e95b0980-9519-11ea-9538-bf68eeb5d1b4.png)

**Comment by tommasoberlose** [comment]
Hey, I thought about this feature but I prefer to keep the widget clear and with limited information visible.
I believe that the focus of Another Widget must remain to show information "at a glance", information that the user can't have from the main UI of the device. And any information about the notifications is easily reachable from the status bar.
