### ISSUE TITLE
FR: Analog clock (option for digital)

### ISSUE THREAD

**Issue by tjsuominen** [tommasoberlose/another-widget#11]
In addition to digital clock, please add an option to have a **simple / minimalistic** analog clock. Just circle (clock table) and min / hour hands.

**Comment by tommasoberlose** [comment]
The AnalogClock widget is deprecated after SDK 23.

**Comment by tjsuominen** [comment]
Ah I see, no worries. Great to have you back and Another Widget back in development!

**Comment by tommasoberlose** [comment]
@tjsuominen thanks!
