### ISSUE TITLE
Capital letter

### ISSUE THREAD

**Issue by Rogmil63** [tommasoberlose/another-widget#113]
**Describe the bug**
Weekday and month are shown in lower case when it is a capital letter

**To Reproduce**

**Expected behavior**
Onsdag instead of onsdag / Maj instead of maj

**Screenshots**
![20200513_170402](https://user-images.githubusercontent.com/65297756/81831480-b1fe5400-953d-11ea-99f1-6096d1a97fd4.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy s9+
 - OS Version: Android 10
 - App Version (that you can find inside the advanced settings) [e.g. v2.0.8(89)]

**Additional context**

**Comment by Rogmil63** [comment]
Hi !
What happen with this issue (capital letter)
Best regards
/Rogmil63

**Comment by tommasoberlose** [comment]
> Hi !
> What happen with this issue (capital letter)
> Best regards
> /Rogmil63

I fixed the issue in the latest beta release.
