### ISSUE TITLE
Displayed alarm doesn't reflect 3rd party alarm app.

### ISSUE THREAD

**Issue by hackthis02** [tommasoberlose/another-widget#115]
I'm using Sleep Like Android at my alarm app and what's displayed on screen seems to always be 7:00.

**Comment by tommasoberlose** [comment]
I get the next alarm from the system. I think that one of your apps is setting an alarm to the 7:00.

**Comment by hackthis02** [comment]
It's not always 7:00am though. It randomly changes throughout the day.

**Comment by tommasoberlose** [comment]
In the latest beta update, you can long-click the "Show next alarm" setting to see which app inserted the wrong alarm.
