### ISSUE TITLE
Settings tied / backed-up to Google account

### ISSUE THREAD

**Issue by tjsuominen** [tommasoberlose/another-widget#116]
There are many settings in AW and it would be great to have them backed up to Google account and restored upon new installation / device.

**Comment by tommasoberlose** [comment]
I've just tested the app backup on a device and it seems to work.
I don't know why it's not working on my OnePlus 5 but I think that could depend on the fact that I used it as my test device.

**Comment by tjsuominen** [comment]
So it should back-up, great!

Just joined AW beta, looking forward to take this to the next level. Just amazing with Niagara launcher!
