### ISSUE TITLE
Alarm shows 5 mins earlier than actual alarm time

### ISSUE THREAD

**Issue by mrrx7** [tommasoberlose/another-widget#117]
When I enable the Next Clock Alarm under Glance section, the alarm is shown as 5 mins before the actual alarm time.

eg. Alarm set for 1600. Widget shows 1555.
Alarm set for 0700. Widget shows 0655.

Note 10+, using default Samsung Clock app to set alarm.

**Comment by mrrx7** [comment]
I installed the Google Clock app and alarms I set with that app show the correct time on the widget.

I think the incorrect time issue must be limited to the Samsung Clock application.

**Comment by tommasoberlose** [comment]
Hey, yeah I think that the problem could be related to the Samsung Clock app.
