### ISSUE TITLE
temperature unchanging despite entering code & geolocation

### ISSUE THREAD

**Issue by lmb02** [tommasoberlose/another-widget#118]
**Describe the bug**
I entered weather API key, set location to "use geolocation", refresh 30 minutes, on tap open "The Weather Channel for Samsung".  Temp is always 72F.  I've restarted widget and restarted phone and no change.  The Weather Channel for Samsung app reports correct location and weather.  If I change from geolocation it correctly reports the temperature and icon for location I enter.

**Expected behavior**
Current temperature and icon when using "geolocation" for weather location.

**Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - OS Version: Android 10
 - App Version v2.0.9 (91)

**Comment by tommasoberlose** [comment]
The API key could take over 20 minutes to be enabled.

**Comment by lmb02** [comment]
I re-installed the key when you first released version 4, weeks ago.  I used the same key that worked in the previous version.  I install your updates as soon as they appear in the Play Store.
App says the "Weather API key" is configured correctly.
I have rebooted the phone, and switched back to "geolocation" in case the problem is that when upgrading to v4, the app recognised geolocation was selected but didn't load the geolocation data properly and act upon it (ran into same problem with the weather app that manages my weather station in that app was set to show constant notification but didn't until I turned constant notification off and then back on).  Will see if that works.
Again, great app!

Michael

---------------
"We're all stories in the end.  Just make it a good one, eh?"
 

    On Saturday, May 16, 2020, 10:12:39 AM PDT, Tommaso Berlose <notifications@github.com> wrote:  
 
 


The API key could take over 20 minutes to be enabled.

**Comment by lmb02** [comment]
Unfortunately, that did not solve the problem.  Allowing for the weather source your app uses and Weather Channel having slightly different temperatures, toggling the geolocation setting did not solve the problem.
Initially, switching to 'geolocation', app showed 68F, Weather channel 66F.
One hour later, app shows 68F, Weather Channel shows 70F.
Switching back to actual location, app shows 71F, Weather Channel shows 70F.

Geolocation seems to get a temperature from somewhere and then does not update.

Going to go back to 'geolocation', but change update interval to '1 hour' to see if that makes a difference.

**Comment by lmb02** [comment]
Allowing full time permission to location solved the problem.

If possible, on the Weather tab, near the top of the options, display the location permissions setting (near the top so one doesn't have to remember to scroll down to see it).

If it is possible to do so, add the ability to set the permission.  If not, then if possible add a link to take one to the tool that allows setting the permission.  At worst, advise the user to go to permissions to set the permission, recommended all the time.

Many thanks!
