### ISSUE TITLE
FR: Custom notes text alignment

### ISSUE THREAD

**Issue by tjsuominen** [tommasoberlose/another-widget#119]
On multi-line (thx for implementing that!) custom notes editor, have ability to align text (2nd line) relative to the 1st row. (Left | Center | Right)

Note: YES, the whole text group should be centered, but the 2nd line aligment should be adjustable.

See image.

![aw](https://user-images.githubusercontent.com/7660277/82113864-c0c55080-9761-11ea-9ab6-21dc6565d208.png)

**Comment by tommasoberlose** [comment]
I think that the custom notes feature must remain really simple.
I'm not planning to insert an advanced text editor for that section and I think that add just the text-align would be not a great design.

**Comment by tjsuominen** [comment]
Agree actually and bad request.
