### ISSUE TITLE
Merge text size and color

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#121]
For more readability, I think you should merge Text size and color. It would become:

- [Title] First row text
  [Subtitle] Size: 26sp, Color: #FFFFFFFF
- [Title] Second row text
  [Subtitle] Size: 18sp, Color: #FFFFFFFF

Size selector can become a cursor like Alpha.

![IMG_20200516_004353](https://user-images.githubusercontent.com/64771681/82117245-31bf3500-976f-11ea-8dc0-48ec87575b53.jpg)

**Comment by tommasoberlose** [comment]
I added a middle header inside every section that divides the different settings.
I think that adding the text size selector to the color picker would make the dialog a little bit too messy.
