### ISSUE TITLE
Please reopen #118 (weather updates), Not solved.

### ISSUE THREAD

**Issue by lmb02** [tommasoberlose/another-widget#122]
**Describe the bug**
Upgraded to 2.0.9 (92).  Still does not update when using 'geolocation'.  Changing update interval to 30 minutes did not help.

If you can reopen #118, this update can be added to that bug report.  Then this report can be deleted and problem determination can be tracked in a single bug report.

Thanks!

**Comment by leoyinjou** [comment]
Are you on Android 10? What is your allowed location permission? Is it on always, or only when app is in use?

**Comment by lmb02** [comment]
Hello,
On the latest Android 10 update that Verizon (US telecom) offers.
Thank you for asking about location permission.  I had thought it was set for all the time, because the widget is running all the time.  Somehow it was set to "off".  I have switched it to "All the time".
Please leave this report open and I will update within 24 hours or less if that has solved the problem.
Thanks for the quick response (and the Battery addition in (92) is nice).

Michael

---------------
"We're all stories in the end.  Just make it a good one, eh?"
 

    On Saturday, May 16, 2020, 9:18:23 PM PDT, leoyinjou <notifications@github.com> wrote:  
 
 


Are you on Android 10? What is your allowed location permission? Is it on always, or only when app is in use?

**Comment by tommasoberlose** [comment]
> **Describe the bug**
> Upgraded to 2.0.9 (92). Still does not update when using 'geolocation'. Changing update interval to 30 minutes did not help.
> 
> If you can reopen #118, this update can be added to that bug report. Then this report can be deleted and problem determination can be tracked in a single bug report.
> 
> Thanks!

Hi, #118 is open but is not locked, so you can always comment and I will receive a notification to reopen the issue.
Let us know if the problem persists after granting the background location permission.
