### ISSUE TITLE
Glance doesn't recognice Spotify Stations songs playing

### ISSUE THREAD

**Issue by tjsuominen** [tommasoberlose/another-widget#125]
**Describe the bug**
Song details not visible at Glance on widget

**To Reproduce**
Listen your music / playlist on Spotify Stations app > Glance doesn't show currently playing info.

**Expected behavior**
See playing info on widget.

**Smartphone (please complete the following information):**
 - Device: OP5
 - OS Version: Android 9.0
 - App Version: 2.0.9 (94)

**Additional context**
Glance info for playing music is shown for e.g. Spotify. Spotify stations is another app (not available globally yet). Works if installed e.g. from APKpure.

**Comment by tommasoberlose** [comment]
I've downloaded the app from APKPure and it seems to work fine.
Do you have any screenshots? Does the app show a notification?

**Comment by tjsuominen** [comment]
Yes, app shows notification and I had no other info visible (no calendar event, no other Glance). Will check back later today.

**Comment by tjsuominen** [comment]
Here's the thing:

1) Spotify Stations song playing and there's a notification
2) No 'Currently playing song' Glance visible; instead shows 'Custom notes' >

I'd expect see Currently playing song and when that's stopped/finished, show custom notes (or others by set the order.

What might have confused me, was the Data source priority (Custom notes was above Currently playing) as the Glance UI does not impact the order defined by the Data source priority... < Why this has to be a seperate setting screen ;)? 

![aw](https://user-images.githubusercontent.com/7660277/82287955-10965880-99aa-11ea-8024-393c61fb7b31.jpg)

**Comment by tjsuominen** [comment]
After re-arranging the glance priorities, this is WAD and can be closed.
