### ISSUE TITLE
Weather Refresh

### ISSUE THREAD

**Issue by sbs8331** [tommasoberlose/another-widget#126]
Any chance of a way to manually refresh the weather from the widget, e.g. an option when tapping the weather?  Sometimes the weather can change significantly in 1/2 hour, and it would be handy to quickly update without launching an app.  As mentioned before, I'd also like to see a service other than (or in addition to) Open Weather Map, which is very inaccurate in my area.  Thanks.  Please stay healthy and safe.

**Comment by shtraus12** [comment]
Same problem. Sometimes weather refreshes only after restarting widget (just opening the app doesn't work).

**Comment by tommasoberlose** [comment]
Did you have granted the background location permission to the app?
I searched for a different free weather provider but they all have strict terms and a low call/day rate.

**Comment by sbs8331** [comment]
I'm just an end user.  I know that some other apps for which I've helped beta test (Chronus, Transparent Clock and Widget) use various services: AccuWeather, Foreca, Yahoo, Weather.com, (decreasingly) Wunderground.  I've heard about issues with free weather providers, so if you can't find a suitable one, I understand.  Would NWS be an option?  If none, just cancel this part of the request if a manual refresh can be incorporated.  No worries either way.  Thanks.

**Comment by Dhrubaof2002** [comment]
> Did you have granted the background location permission to the app?
> I searched for a different free weather provider but they all have strict terms and a low call/day rate.

What if I add a specific address manually ?

**Comment by S-Shen** [comment]
v2.0.12 
LinageOS 17.1
OnePlus 3T

Same issue
Weather does not auto refresh if location was manually set and location permission was not granted

It works fine with geolocation, however app doesn't prompt for permission when selecting 'using geolocation'. Have to manually grant permission in system settings
