### ISSUE TITLE
English translation fix

### ISSUE THREAD

**Issue by LastInLine** [tommasoberlose/another-widget#128]
**Describe the bug**
Calendar > Time left update frequency

Description reads "High frequency cause more battery consume", should read "High frequency **causes** more battery **consumption**"

I'm sorry, if I knew how to look through the strings and submit pull requests, I would...

**Comment by tommasoberlose** [comment]
Hey! You could view the file strings.xml [here](https://github.com/tommasoberlose/another-widget/blob/master/app/src/main/res/values/strings.xml) that contains the English version of the app strings.
You could edit the file directly on GitHub with the pencil icon and create a pull request to submit your changes.
