### ISSUE TITLE
All options for Calendar > Show events at least aren't visible

### ISSUE THREAD

**Issue by LastInLine** [tommasoberlose/another-widget#132]
**Describe the bug**
Under the Calendar tab, Show events at least the user is presented with options ranging from 30 minutes up to 24 hours later.  There used to be options for 3 days and 7 days later.  I don't know if it's intended behavior for the upper limit to be 24 hours, but as I had it set for 3 days prior to the update which added options my install still shows 3 days.

**To Reproduce**
1. Go to Calendar tab
2. Click on Show events at least under the Filter subheading
3. The popup only shows up to 24 hours later

**Expected behavior**
I'd expect to see the full range of options

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - OS Version: Android 10, May 2020 update
 - App Version 2.0.9 (96)

**Additional context**
Could be intentional and because I was previously set to a deprecated duration I got to keep it that way.  I posted this because the 3 day and 7 day strings still exist in the strings.xml and I wasn't sure if they were supposed to be visible.

**Comment by tommasoberlose** [comment]
I have removed a few options in the past updates because having a big range for the possible future events caused a few issues. But I actually changed how I store and react to future events in the latest version of the app... so I think that I could restore the missing options in a future update.
