### ISSUE TITLE
Date Format not working

### ISSUE THREAD

**Issue by tko735** [tommasoberlose/another-widget#133]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6]
 - OS Version: [e.g. Android 9.0]
 - App Version (that you can find inside the advanced settings) [e.g. v2.0.5 (71)]

**Additional context**

**Comment by tommasoberlose** [comment]
Hey, could you be a little more specific about the issue? Thank you

**Comment by tko735** [comment]
My system is 
Huawei p30 pro
Android 10
EMUI 10

When I pressed Date Format button, there is nothing happen. For the old version, it will show the format of how to display date.

**Comment by tommasoberlose** [comment]
That's odd ... when you tap on the "Date format" setting it should be shown a bottom dialog menu with the default option and the possibility to open a new page to create a custom date format.
Does the dialog show up?

**Comment by tko735** [comment]
Nothing shows up.

**Comment by badener95** [comment]
Same for me. I am using a Google Pixel 3a with Android 10. The device is set to German language and the default date formatting for this widget is completely fine and apperently also region specific, but if I wanted to change it I couldn't. Selecting the option simply doesn't do anything.

**Comment by tommasoberlose** [comment]
> Same for me. I am using a Google Pixel 3a with Android 10. The device is set to German language and the default date formatting for this widget is completely fine and apperently also region specific, but if I wanted to change it I couldn't. Selecting the option simply doesn't do anything.

Does the dialog show up at least?
