### ISSUE TITLE
Add on/off button to visible/hidden options

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#136]
Add on/off button to every visible/hidden options, except Custom notes (screenshot 2 to 6).
Make them clickable only once: because opening the selector everytime is tiring (screenshot 1).

![Screenshot_2020-05-19-21-21-25-804_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/82369892-fc894000-9a17-11ea-9376-eba411ddc778.jpg)

![IMG_20200519_212717](https://user-images.githubusercontent.com/64771681/82369927-04e17b00-9a18-11ea-94ad-494c35e971e9.jpg)
![IMG_20200519_212811](https://user-images.githubusercontent.com/64771681/82369932-057a1180-9a18-11ea-8cab-1716b8ff01fc.jpg)
![IMG_20200519_212834](https://user-images.githubusercontent.com/64771681/82369934-0612a800-9a18-11ea-8926-ec45423fe454.jpg)
![IMG_20200519_212943](https://user-images.githubusercontent.com/64771681/82369935-0612a800-9a18-11ea-9473-f0e56900806a.jpg)
![IMG_20200520_181726](https://user-images.githubusercontent.com/64771681/82471134-95769480-9ac6-11ea-887f-2cbc5b3cdaac.jpg)

**Comment by tjsuominen** [comment]
👍
