### ISSUE TITLE
Follow the system theme (missing button)

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#141]
**Describe the bug**
The default theme should be Follow the system theme. But when I click on it, it is Set by batteey saver.

**To Reproduce**
1. Go to 'Settings' (top right button)
2. Click on 'Theme'
3. See messed up options

**Expected behavior**
Theme options should be:
- Light
- Dark
- Set by battery saver
- Follow the system theme

**Screenshots**
![Screenshot_2020-05-20-18-18-22-978_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/82471555-1e8dcb80-9ac7-11ea-9507-d817d46186d0.jpg)

**Smartphone**
 - Device: Xiaomi Redmi Note 7
 - OS Version: Android 9 with MIUI 11
 - App Version: 2.0.11 (100)

**Comment by tommasoberlose** [comment]
Based on this [doc](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#changing_themes_in-app) I select as default option `MODE_NIGHT_AUTO_BATTERY` on pre-Android 10 devices and `MODE_NIGHT_FOLLOW_SYSTEM`on Android 10+ devices.
