### ISSUE TITLE
Xiaomi Devices pop-up is wrong for me

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#144]
**Describe the bug**
I disactivated the option mentionned in the pop-up for Xiaomi Devices. I still can open Calendar and Weather. I didn't tested for Glance yet.
The only problem is Clock: when set on Default, nothing happens (Xiaomi pop-up option activated or not) and I must select munually an app.

Maybe I'm an exception, please other Xiaomi users test it and send a feedback here.

**Expected behavior**
Make the button 'Tap on ... opens' red text with a red dot, so everyone must select an app. 
Remove Default app option, or set Xiaomi's Clock app by default for Xiaomi devices in your code (idk if it will work).
Remove Xiaomi Devices pop-up, if every Xiaomi users are in the same case as me.

**Screenshots**
![Screenshot_2020-05-20-22-34-29-036_com miui securitycenter](https://user-images.githubusercontent.com/64771681/82495811-011f2880-9aec-11ea-8f02-f4b2781c2ec3.jpg)
![Screenshot_2020-05-20-22-39-56-533_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/82495819-02505580-9aec-11ea-80b3-29831c3dd429.jpg)

**Smartphone:**
 - Device: Xiaomi Redmi Note 7
 - OS Version: Android 9 with MIUI 11
 - App Version: 2.0.11 (100)

**Comment by tommasoberlose** [comment]
The issue of the missing permission occurs only on Xiaomi devices, but I can't detect on which devices is present. I can check if there's a default clock application, though.
