### ISSUE TITLE
Option to add time (fixed value) to alarm (Adjust alarm time)

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#153]
**Is your feature request related to a problem? Please describe.**
For me, the alarm displayed in the widget is 1h before the actual alarm time. I read that some users have it 5min before.

**Describe the solution you'd like**
An option to add a fixed value of time to the alarm that is displayed in the widget to match the actual alarm time. 
This value would be for all alarm displayed in the widget and the value can be changed anytime in the widget settings.

If you add the option 'Adjust alarm time' to the app, then make it gray/disactivated when 'Show next alarm' is set on Hidden (just like Time until event update frequency).

You can make the button 'Adjust alarm time' like you made the 'Date format' button: 
- Option 1: Default (no adjustment)
- Option 2: Custom adjustment. Opens a new page with a type zone (+/-, number of hours, number of minutes) and a little text (bottom of page) to explain why some devices need to adjust alarm time.

**Comment by tommasoberlose** [comment]
Please refer to #158
