### ISSUE TITLE
Tap on Glance does

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#155]
Tap on Glance does:
- Open displayed app provider
- Change provider (like a switcher)

**Why 'Tap on' and not an actual switcher?**
Because the Glance line is too short and an actual swutcher is not suitable (i remember the former multiple event switcher from v1, it was never easy even with small fingers)

**Comment by tommasoberlose** [comment]
I originally developed the Glance section as a feature that helps the user without his interaction, like the Google's At a Glance widget is designed.
I think that a "switch" option could create confusion with the order of the providers and remove the actual power of the feature: to show the provider data when you more need them.
