### ISSUE TITLE
Pressing date - wrong place in calendar

### ISSUE THREAD

**Issue by sequelae75** [tommasoberlose/another-widget#159]
**Describe the bug**
Pressing on the date on the widget direct me to the wrong date and year on the calendar app.

**To Reproduce**
1. Go to home screen
2. Click on date on the widget
3. Direct to wrong date and year

**Expected behavior**
Expected to be directed to the date and year of today

**Screenshots**
![Screenshot_20200523-104101__01](https://user-images.githubusercontent.com/64898355/82726254-072b2a00-9ce3-11ea-8e8f-805398b7423d.jpg)
![Screenshot_20200523-104106__01](https://user-images.githubusercontent.com/64898355/82726256-085c5700-9ce3-11ea-97cc-0960471d1020.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS Version: Android 10.0
 - App Version v2.0.12 (102)

**Comment by tommasoberlose** [comment]
Do you tap on the date when there are no events or the date that shows up when you have an all-day event?
