### ISSUE TITLE
Please Reopen # 150. Current Playing Song in Glance.

### ISSUE THREAD

**Issue by AkshatV94** [tommasoberlose/another-widget#164]
The current playing song option, enabled from the Glance menu is not updating with the change in track. I am using Black Player EX as music player. The issue was originally raised in Issue #150 which was closed for release 2.0.12. But after updating to version 2.0.12 (102), the issue still persists.

Edit: Selecting an app from the notification shade and going back to home screen tends to change the Current Playing Song. But still not the way it should be.

 - Device: OnePlus 6
 - OS Version: Android 10.0
 - App Version: 2.0.12 (102)

**Comment by tommasoberlose** [comment]
Hi @AkshatV94 , I think that this problem could be related to an Android bug that kills the notification listener service and blocks the app to receive updates on the current playing song.
