### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Dhrubaof2002** [tommasoberlose/another-widget#165]
Add more weather providers like AccuWeather , Weather.com , etc if possible .

**Comment by MarcusOptimus** [comment]
Yes, I'd like to see them too, especially AccuWeather.

**Comment by tommasoberlose** [comment]
Hey guys, I've just added a few new weather providers in the new beta version.
I'm still working on the AccuWeather support but it seems that the APIs don't permit a lot of day requests. Are you going to use a "premium" account? Or do you want to use a freemium one?

I'm trying to figure out how to handle the limit and to reduce the APIs calls.
