### ISSUE TITLE
shadow on the clock

### ISSUE THREAD

**Issue by MarkusSela** [tommasoberlose/another-widget#166]
In colourful backgrounds the time It is not seen clearly.
With the same type of shadow that the date and the weather have can solve the problem.

**Comment by tommasoberlose** [comment]
Hi @MarkusSela due to technological restrictions it's not possible to add the text-shadow to the clock.
You could add a background to the widget, although I know that it's not the nicest solution.

**Comment by asrajo** [comment]
can you incrase the background padding? so that linear with icons above it widget
