### ISSUE TITLE
Calendar and date

### ISSUE THREAD

**Issue by OmShejul** [tommasoberlose/another-widget#167]
Ability to see date as well as the upcoming meeting would be great. As it is convenient date but I also don't want to miss a meeting

**Comment by tommasoberlose** [comment]
Hi @OmShejul thanks you for the feedback but right now the widget supports only two rows due to design restrictions.

**Comment by Nxt3** [comment]
@tommasoberlose What about adding the calendar stuff as part of the second row? It stinks that we lose the date when an event is showing
