### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by hamydansari** [tommasoberlose/another-widget#170]
**Describe the bug**
![Screenshot_20200604-160405_Nova Launcher](https://user-images.githubusercontent.com/37932594/83754911-cd143d80-a67d-11ea-8ad2-65d8f5c6b59c.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6]
 - OS Version: [e.g. Android 9.0]
 - App Version (that you can find inside the advanced settings) [e.g. v2.0.5 (71)]

**Additional context**

**Comment by leoyinjou** [comment]
I have reported this in closed issue #104 
Please read the responses in there.
