### ISSUE TITLE
Option to hide multi-day events

### ISSUE THREAD

**Issue by tjsuominen** [tommasoberlose/another-widget#171]
**Is your feature request related to a problem?
If I have an event starting say Monday 10am continuing untill say Thu 4pm I would not like to have it visible all the time.

**Describe the solution you'd like**
An option to hide events longer than 1d.

**Describe alternatives you've considered**
Full day events hiding option doesn't cover this usecase.

**Additional context**
N/A

**Comment by tommasoberlose** [comment]
@tjsuominen I think that could be difficult to filter the events that start in one day and finish in the next one but that are just something overnight instead of those events the are similar to all day events.

**Comment by tjsuominen** [comment]
Understood.
