### ISSUE TITLE
All day events showing in the widget

### ISSUE THREAD

**Issue by pratnala** [tommasoberlose/another-widget#174]
**Describe the bug**
All day events showing in the widget even when I have them disabled.

**To Reproduce**
Have some all day events on the calendar and it will show them sometimes on the previous day and sometimes when another event is going on.

**Expected behavior**
They should not show.

**Screenshots**
Can't share on public forum but happy to email

**Smartphone (please complete the following information):**
 - Device: Galaxy S20 Ultra
 - OS Version: Android 10
 - App Version (that you can find inside the advanced settings) 2.0.12 (102)

**Comment by tjsuominen** [comment]
Also when having an event starting say Monday at 10am and ends at Thu 6pm. Would like to have it not to show.

**Comment by EKatowitz** [comment]
I have the same issue.    Even with "All day events" set to hidden they still show up.

In fact an all day event for tomorrow seems to take priority over normal events that are occurring today.

**Comment by pratnala** [comment]
> I have the same issue.    Even with "All day events" set to hidden they still show up.
> 
> 
> 
> In fact an all day event for tomorrow seems to take priority over normal events that are occurring today.

Yes, this is exactly what is happening.

**Comment by pratnala** [comment]
Hey, @tommasoberlose! Any update on this please?

**Comment by Radixtrator** [comment]
I am having the same issue. It's the only issue I have with it but it keeps me from using the widget . @tommasoberlose any updates?

**Comment by kaprijela** [comment]
At least for me, the widget appears to hide today's all-day evets as agreed in the settings, but shows tomorrow's all-day events. I'll try to look into it as soon as I get my Android Studio working correctly.

**Comment by samuryan89** [comment]
Same issue here. My work requires us to have an all day event with our schedule in it, which I'd prefer to not see every day. Without this feature working correctly, this widget doesn't work for me.
