### ISSUE TITLE
GrapheneOS: Weather not showing & Disappearing widget text

### ISSUE THREAD

**Issue by Kartereo** [tommasoberlose/another-widget#175]
**Describe the bug**
The weather doesn't show even though it says the key is configured correctly. Also the the text on the widget stops showing after a while.

**To Reproduce**
1. Setup as you normally would and enter weather key.

**Expected behavior**
The weather should show on the widget.
The text shouldn't disappear on the widget.

**Screenshots**
![Screenshot_20200616-190017](https://user-images.githubusercontent.com/5624644/84836410-b36ee080-b003-11ea-9339-ddc47e901c63.png)
![Screenshot_20200616-190032](https://user-images.githubusercontent.com/5624644/84836423-b669d100-b003-11ea-8e93-aab1222e3329.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3 XL
 - OS Version: GrapheneOS (Build QQ3A.200605.001.2020.06.02.02)
 - App Version: 2.0.12

**Additional context**
This app was downloaded through the Aurora Store. No Google services are present on this device. All permissions have been granted to the app.

**Comment by tommasoberlose** [comment]
Hi @Kartereo I'm afraid that Google services are mandatory.
