### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by RahManJunior** [tommasoberlose/another-widget#176]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Greetings such like in Lawnchairs V2's at a glance native widget.
EG: "Good morning!" in morning
"Have a good day!" in afternoon
"Charge your phone" when low battery
"Sleep well" at night
"Don't go to bed too late" at very late night
Things like this :)

**Describe alternatives you've considered**
Going back to Lawnchair

**Additional context**
https://i.imgur.com/lbmvw14.jpg
https://i.imgur.com/taE498v.jpg

**Comment by MarcusOptimus** [comment]
It would be nice. And it would also be nice to have new providers to show other types of informations. :)

**Comment by tommasoberlose** [comment]
Hi there, this could be a really good idea but I think that it'll be very hard to support with partial language support.

**Comment by Moutony** [comment]
> Hi there, this could be a really good idea but I think that it'll be very hard to support with partial language support.

Maybe you can make it change during the day (morning, noon, evening, night) like on Apple lockscreens.
For each period, you can make a random greeting that display one of the few messages that you already wrote.

Example for Morning: 
- Good morning! 
- Did you sleep well? 
- Have a nice day!
- Rise and shine! Today is a sunny day. (related to weather)
- Do you want to build a snowman? (related to weather)

**Comment by tommasoberlose** [comment]
I've just added the Greetings as a Glance provider in the latest beta.
Everyone could add some string resources in each language file and they will be shown randomly.
