### ISSUE TITLE
The Widget doesn't refresh automatically

### ISSUE THREAD

**Issue by shdreamer** [tommasoberlose/another-widget#177]
The Widget doesn't refresh automatically. The only way to refreshis to open the App. After opening it refreshes in the App and also in the Homescreen.

**To Reproduce**
Open App
The Preview refreshes and so does the widget
Without opening no refreshing

**Expected behavior**
I expect an automatic refreshing of the widget

**Screenshots**
No Screenshots to explain

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS Version: Android 10
 - App Version (that you can find inside the advanced settings) 2.0.12 (102)

**Additional context**
Thanx for your Work ;-)

**Comment by tjsuominen** [comment]
Hmmm... Refreshes automatically for me (OP5, Android 9). Something to do with access rights or Android 10 on Samsung?

**Comment by MarcusOptimus** [comment]
Same problem with my Pixel 3 with Android 10.

**Comment by tommasoberlose** [comment]
@shdreamer @MarcusOptimus did you try to remove Another Widget from the battery optimization app list?
