### ISSUE TITLE
Weather icon cropped 

### ISSUE THREAD

**Issue by drownedboys** [tommasoberlose/another-widget#181]
When the text separator is disabled, the left side of weather icon is slightly cropped. 

![IMG_20200704_225402](https://user-images.githubusercontent.com/67842603/86520841-48b60580-be49-11ea-8c79-c617fa19040b.jpg)

**Comment by GCrane1982** [comment]
I have noticed the same issue however it is cropped at the top. It would be great to be able to manually adjust the gap in between the first and second line.

![Screenshot_20200710-084450_One UI Home](https://user-images.githubusercontent.com/68087359/87100165-d307ca80-c28a-11ea-83d9-c9dad72f6096.png)

**Comment by tommasoberlose** [comment]
Hi there, I tried to reproduce the bug but I wasn't able to do it. Could you please share with me the text sizes that you're using?
Thanks

**Comment by GCrane1982** [comment]
[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20201003-062050_Another_Widget_png_1601671866849]



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by drownedboys** [comment]
It happens with certains weather icons.
I attach a screenshot of my settings but with this cloudy icon, it looks ok.



—
손우성
Woosung Sohn
http://woosungsohn.com/

**Comment by Moutony** [comment]
I noticed that the temperature unity (°C) was cropped when the date name is too long (e.g: Dimanche 27 Septembre, with 24pt size)

**Comment by tommasoberlose** [comment]
Hi guys, could you please check if this bug is still present in the latest beta version?

**Comment by Manneman32** [comment]
Looks ok now!

**Comment by Moutony** [comment]
It's still cropped for icon pack 1

![Screenshot_2020-10-14-18-54-38-206_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96024531-23776100-0e54-11eb-875c-f88055d7f72e.jpg)
![Screenshot_2020-10-14-18-54-41-737_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96024532-240ff780-0e54-11eb-9edf-f9cdea619e54.jpg)

**Comment by GCrane1982** [comment]
It's looking better from my end but will keep an eye on it throughout the day and let you know if I notice any issues.

As you have added in more weather sources is there any chance you could add and Australian Weather source?

https://www.programmableweb.com/api/australian-bureau-meteorology

https://www.willyweather.com.au/info/api.html


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by Moutony** [comment]
> It's looking better from my end but will keep an eye on it throughout the day and let you know if I notice any issues. As you have added in more weather sources is there any chance you could add and Australian Weather source? https://www.programmableweb.com/api/australian-bureau-meteorology https://www.willyweather.com.au/info/api.html Sent from my Samsung Galaxy smartphone.

Ahem, programmableweb don't look like a dedicated website for weather so it's risky.

**Comment by GCrane1982** [comment]
Sorry they were the links to the API, below are some links to the actual weather sites

http://www.bom.gov.au/
https://www.willyweather.com.au/
http://weatherzone.com.au/

Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by Moutony** [comment]
> It's still cropped for icon pack 1, EVEN with text separator.
> Solution 1: shrink a little the icons of pack 1.
> Solution 2: change the position of icons a little.

**Update**
Everything is okay in dark mode!
The problem seems to be in light mode only.

![Screenshot_2020-10-14-23-44-54-104_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96048878-86c6ba80-0e77-11eb-9aa5-066ddcbdfb32.jpg)

**Comment by Moutony** [comment]
> It's still cropped for icon pack 1, EVEN with text separator.
> Solution 1: shrink a little the icons of pack 1.
> Solution 2: change the position of icons a little.

**Update**
Everything is fine in dark mode!
The problem seems to be only in light mode.
It is strange because i set the same text size and color.

Solution: compare position/margin attributes between light and dark mode in your code and guess the error.

![Screenshot_2020-10-14-23-44-54-104_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96049289-18cec300-0e78-11eb-9be1-98a284fff011.jpg)
![Screenshot_2020-10-14-23-47-31-559_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96049292-19675980-0e78-11eb-8273-996a59db1034.jpg)

**Comment by GCrane1982** [comment]
Yeah I'm still seeing a slight crop using the icon pack 1

[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20201015-101438_One_UI_Home_png_1602719144706]



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by tommasoberlose** [comment]
> Sorry they were the links to the API, below are some links to the actual weather sites http://www.bom.gov.au/ https://www.willyweather.com.au/ http://weatherzone.com.au/ Sent from my Samsung Galaxy smartphone.
> […](#)
> -------- Original message -------- From: Moutony <notifications@github.com> Date: 15/10/20 7:06 am (GMT+09:30) To: tommasoberlose/another-widget <another-widget@noreply.github.com> Cc: GCrane1982 <geoffrey.crane@live.com>, Comment <comment@noreply.github.com> Subject: Re: [tommasoberlose/another-widget] Weather icon cropped (#181) It's looking better from my end but will keep an eye on it throughout the day and let you know if I notice any issues. As you have added in more weather sources is there any chance you could add and Australian Weather source? https://www.programmableweb.com/api/australian-bureau-meteorology<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.programmableweb.com%2Fapi%2Faustralian-bureau-meteorology&data=02%7C01%7C%7Cd936088792eb42cffec008d87080dff0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637383046095719688&sdata=aNao7TosVV0cPLQqNccLHf3Xltfffa420nD4xGw3lH8%3D&reserved=0> https://www.willyweather.com.au/info/api.html<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.willyweather.com.au%2Finfo%2Fapi.html&data=02%7C01%7C%7Cd936088792eb42cffec008d87080dff0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637383046095729681&sdata=p0sOno5sRQMm3DUWSHWXlqviOAV3WVc%2FwqKbYe%2BGOss%3D&reserved=0> Sent from my Samsung Galaxy smartphone. Ahem, programmableweb don't look like a dedicated website for weather so it's risky. — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftommasoberlose%2Fanother-widget%2Fissues%2F181%23issuecomment-708646168&data=02%7C01%7C%7Cd936088792eb42cffec008d87080dff0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637383046095729681&sdata=CMbHGYrpcdtaK8HDDloRVPX5zJZqCnIfCsko4VrzzjE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQHO4P36WUARKIONNVU5T2DSKYDWBANCNFSM4OQRVJAQ&data=02%7C01%7C%7Cd936088792eb42cffec008d87080dff0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637383046095739678&sdata=qcyj43eDfHu2n6iqIRWUfHWeLVJZKjPp%2FIyXIr%2BN7Fw%3D&reserved=0>.

@GCrane1982 I already looked at the BOM API but they don't offer a REST service. I've just checked the other providers that you suggested but they are paid services, so I think that no a lot of people would use them.

**Comment by tommasoberlose** [comment]
Oook I've just found out the problem.
I made a mistake exporting the icons from my sketch file:

![image](https://user-images.githubusercontent.com/9036548/96247891-00ab9080-0fab-11eb-8098-b3a5d6f4ebd0.png)

The dark version of the app was fine and that's why the problem was present only when the dark theme was turned off.
This bug was driving my crazy!

**Comment by GCrane1982** [comment]
Not sure about you guys but I am still seeing the icons getting cropped. I know you said you found problem but was it actually fixed?

[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20201119-070818_One_UI_Home_png_1605731909406]



Sent from my Galaxy



-------- Original message --------

**Comment by Moutony** [comment]
> Not sure about you guys but I am still seeing the icons getting cropped. I know you said you found problem but was it actually fixed? [cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20201119-070818_One_UI_Home_png_1605731909406]
> […](#)
> Sent from my Galaxy

It has been fixed in the lastest BETA version.

**Comment by drownedboys** [comment]
I'm on beta version but the bug is still there

**Comment by GCrane1982** [comment]
The icon issue is fixed for me however I am seeing a couple of other issues with the beta version. 1 is that my Galaxy S10+ is reporting high battery usage for the app and the other is that whenever I snooze a calendar reminder it come up saying that AnotherWidget has stopped responding and asks me to close the app

Regards,
Geoff Crane
Mobile: 0418 468 629


Sent from my Galaxy



-------- Original message --------
