### ISSUE TITLE
Resizing to subgrid sizes

### ISSUE THREAD

**Issue by reidjim76** [tommasoberlose/another-widget#187]
**Is your feature request related to a problem? Please describe.**
When using a launcher that supports subgrid layout (i.e. Microsoft Launcher), the minimum widget height is still 1 row. Since the actual widget info is pretty small, this results in a waste of space. 

**Describe the solution you'd like**
I would like to be able to resize it down to a half row so as to give me more space on the screen. An example of this is the "Time & Weather" widget included with Microsoft Launcher.

**Describe alternatives you've considered**
I've found no alternatives to make Another Widget resize to less than one full row.

**Additional context**
Another Launcher minimum height
![Screenshot_20200818-114621](https://user-images.githubusercontent.com/28219302/90535310-c2c7f280-e148-11ea-94c2-738763387475.png)

Microsoft Launcher Time & Weather widget minimum height
![Screenshot_20200818-114718](https://user-images.githubusercontent.com/28219302/90535381-d4a99580-e148-11ea-8857-db96625c9713.png)

**Comment by saschaeggi** [comment]
Can we get it at least to resize to 1 row height? On a very tall screen like on the OnePlus Nord it's very big and could be more compact so 1 row height would be enough. But I'm not able to resize it down to 1r.
![Screenshot_20200930-220307](https://user-images.githubusercontent.com/5558166/94734180-2741b880-0369-11eb-893a-1c5390e73e71.jpg)
![Screenshot_20200930-220255](https://user-images.githubusercontent.com/5558166/94734196-2d379980-0369-11eb-8485-5ddc0019e747.jpg)

**Comment by saschaeggi** [comment]
Thanks a lot, works like a charm! 👍 💯
