### ISSUE TITLE
Add the option to enable "Glance" as an additional row

### ISSUE THREAD

**Issue by racuna** [tommasoberlose/another-widget#189]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem. But I have events almost every day in calendar (like local holydays, meetings, or even current moon phase). So, almost never "Glance" tab information appears at the screen.

**Describe the solution you'd like**
Glance information (e.g.: daily steps) appears only if there is no events on the calendar. Should be cool to add an additional row with that "non essencial" info as well, even when there is events on the calendar.

**Comment by tommasoberlose** [comment]
Hi @racuna thanks you for the suggestion but right now the widget supports only two rows due to design restrictions.
