### ISSUE TITLE
Wrong RTL alignment and click actions switch

### ISSUE THREAD

**Issue by YanovskyOr** [tommasoberlose/another-widget#19]
When using right-to-left lenguages (e.g. Hebrew), the widget won't align to the right as in the preview. Also, clicking the weather opens calendar and vice versa. 

![screenshot_20171202-142533](https://user-images.githubusercontent.com/21991428/33515613-578838c2-d76e-11e7-96d6-040963ea70b7.png)

![screenshot_20171202-142542](https://user-images.githubusercontent.com/21991428/33515612-5769dda0-d76e-11e7-9cf2-9c8342977b00.png)

**Comment by tommasoberlose** [comment]
Fixed in version 2.0.2.
