### ISSUE TITLE
Lock Screen Support

### ISSUE THREAD

**Issue by seesemichaelj** [tommasoberlose/another-widget#190]
**Is your feature request related to a problem? Please describe.**
The reason why I'm giving Another Widget a try is that I mainly use At a Glance from the lock screen for quick "at a glance" information. It seems that Another Widget is only a widget and doesn't support the lock screen, is this correct?

**Describe the solution you'd like**
I'd love to see the Another Widget to replace At a Glance information on the lock screen. I'm not sure if this is even technically feasible.

**Describe alternatives you've considered**
For me, my alternative is to not use Another Widget and deal with the issues At a Glance has.

**Comment by seesemichaelj** [comment]
FWIW, I believe I found a workaround by using the [Lockscreen Widgets](https://play.google.com/store/apps/details?id=tk.zwander.lockscreenwidgets) app

**Comment by tommasoberlose** [comment]
Hi @seesemichaelj , the newest versions of Android don't support the lock screen widgets as a supported feature. The app that you're using is actually replacing the OS lock screen.
