### ISSUE TITLE
Weather didn't update / show up

### ISSUE THREAD

**Issue by hilmihisham** [tommasoberlose/another-widget#2]
The first time I install the app, the weather stayed at 17°C at all time.. then try to reinstall the app and now it didn't even showed up anymore.. Calendar was okay both time.

**Comment by angelapg14** [comment]
Same issue. Weather not showing. Reinstalled but still no weather info on widget.

**Comment by garpunkal** [comment]
It didn't show for me initially and then I realised I had spaces in the API key...  potentially need to trim this string?

**Comment by tkrauthoff** [comment]
Author mentioned, that there are too many request. Do you guys have your own OpenWeather Api Key?

**Comment by hilmihisham** [comment]
sorry, forgot to close the issue. it's actually have been fixed long ago using openweather api key.. thanks!
