### ISSUE TITLE
Include ''Data source priority'' in the principal Glance page

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#201]
**Is your feature request related to a problem? Please describe.**
It is not very relevent atm: we must click on ''data source priority'' to see how Glance is sorted.

**Describe the solution you'd like**
Include the moving button in the main page (like in the picture).
Add a text in the (i) to explain how to do.

**Describe alternatives you've considered**
Keep the buttons like they are.
But reorganize the Glance Providers everytime the user change the priority.

**Additional context**
![IMG_20201005_174839](https://user-images.githubusercontent.com/64771681/95126204-5e8fdb00-0756-11eb-80ad-0fb8a008dfbb.jpg)

**Comment by tommasoberlose** [comment]
I'm actually very busy working on some other features right now, but I've already thought about a few UI updates of the Glance section. This was for sure one of the updates I'd implement.

**Comment by tommasoberlose** [comment]
Introduced in the latest beta.
