### ISSUE TITLE
The alarm timings on the another Widget is not correct, it shows completely random alarm timings that aren't even set by me (the user)

### ISSUE THREAD

**Issue by tejasrao20** [tommasoberlose/another-widget#202]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6]
 - OS Version: [e.g. Android 9.0]
 - App Version (that you can find inside the advanced settings) [e.g. v2.0.5 (71)]

**Additional context**

**Comment by tommasoberlose** [comment]
Please refer to #158
