### ISSUE TITLE
All day events should have an option to not show event info

### ISSUE THREAD

**Issue by LastInLine** [tommasoberlose/another-widget#203]
**Is your feature request related to a problem? Please describe.**

I frequently set a multi-day all day event to denote vacation.  The problem is that once I'm on vacation for the entirety the widget will display the date as the start date of the event meaning there isn't an easy way to view the current date and worse, it prominently displays a date that is increasingly in the past.

**Describe the solution you'd like**

I think the best way to address multi-day event date spans would be to add an option to "Hide event info for all day events" which could be placed under Calendar > Event Detail below Event Info.

I suggest this because a user who chooses to show all day events is likely doing so because they want to know it's both upcoming and ongoing, but I doubt they care about the start date once it has begun.  Further, I suspect for such multi-day events the user is likely to leave the address field blank for a number of reasons so the Event Info is likely to be always showing the event start date.

**Describe alternatives you've considered**

1. One alternative would be for the user to use the "Relevant Event" feature to filter events.  The disadvantage here is that then the event would not be visible when it is upcoming which is presumably why it's on the calendar and the user has made it visible on the widget to begin with.

2. Another alternative would be to optionally show the event as upcoming but hide the event once it is in progress, but I could see how that might not be desired since if the user has chosen to keep all-day events visible they might not want it to disappear at midnight on the day it begins so perhaps adding an option to only show on the first day would be useful if this route is taken.  A suggested UI for this would be to change Calendar > Filters > All Day Events from a toggle to a selection window with the options "Hidden"  "Visible only while upcoming" "Visible through first day only" and "Visible throughout entire event". 

I don't really like this idea because it seems harder and I still imagine that a user choosing to make all day visible wants to see that event displayed while it's ongoing.  I feel like it's the start date that's irrelevant information, not the event title.

**Additional context**
This is definitely a corner case and I understand if it seems like too much work for too little gain.

**Comment by tommasoberlose** [comment]
@LastInLine Thank you for your feedback, I agree that multi-day events are really difficult the handle due to different user-case situations. I actually hide the all-day events on my phone to avoid viewing the same event every day. (I've also hidden the multi-event switcher)

I've just updated the function that shows the event detail to show the start date when the event is upcoming and the actual date when the event is ongoing. Could it be a suitable solution for you? The other options that you suggested are very interesting but I think that could be a big effort for a corner case, as you said.

**Comment by LastInLine** [comment]
@tommasoberlose LOL, when I was creating the issue I had originally written that it should be exactly that.  When I got to the alternatives section, I thought of just not showing the info so I changed everything to that because I figured it'd be easier for you!

I like your solution.  I think it makes more intuitive sense and even better, no UI to change!

**Comment by tommasoberlose** [comment]
@LastInLine Haha, very good! I think I'll post the new beta version in a few days.
Thank you again.
