### ISSUE TITLE
Default calendar app

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#205]
**Describe the bug**
It always shows me ''Horloge'' (=Clock) in default calendar app, while I set Google Calendar.
NB : When I click on the widget, the correct default calendar app (Google Calendar) opens.

**Expected behavior**
Display the correct default calendar app.

**Screenshots**
![Screenshot_2020-10-12-06-47-03-065_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/95706450-3113c780-0c57-11eb-9d9a-95081bf64232.jpg)

**Smartphone**
 - Device: Xiaomi Redmi Note 7
 - OS Version: Android 10
 - App Version: v2.0.14(106)

**Comment by tommasoberlose** [comment]
Fixed, thank you for the feedback.
