### ISSUE TITLE
Widget says "Charged" when phone is charging

### ISSUE THREAD

**Issue by pratnala** [tommasoberlose/another-widget#207]
**Describe the bug**
Widget says "Charged" when the phone is still charging

**To Reproduce**
1. Connect your phone to your charger
2. Look at the widget

**Expected behavior**
The widget should say "Charging".

**Smartphone (please complete the following information):**
 - Device: Galaxy S20 Ultra
 - OS Version: Android 10 
 - App Version (that you can find inside the advanced settings): 2.0.13

**Additional context**
It says "Charged - 100%" when it is done.

**Comment by tommasoberlose** [comment]
Fixed.
