### ISSUE TITLE
Tons of wakelocks

### ISSUE THREAD

**Issue by Madis0** [tommasoberlose/another-widget#21]
Another Widget seems to cause a lot of wakelocks, and that was even before I enabled weather.
![](https://i.pi.gy/qJ1oQ.jpg)

Checked with [Wakelock Detector Lite](https://play.google.com/store/apps/details?id=com.uzumapps.wakelockdetector.noroot). Any ideas? 

Edit: what I posted above is actually "wake-up triggers", which still seem abnormally high compared to other apps. Image below shows actual CPU wakelocks, which only sum up to 2 seconds but were executed 131 times.

![](https://i.pi.gy/pjDxR.jpg)

**Comment by tiagobt** [comment]
Same problem here (OnePlus 3 running Android 8.0.0 and OxygenOS 5.0.3).

Here are some screen capture showing the issue:

**1. Wakelock Detector Full - CPU Wakelock**

![wld-cpu-wakelock](https://user-images.githubusercontent.com/593900/42602743-37d8c1f0-8541-11e8-8261-a1c5ac0c7465.jpg)

**2. Wakelock Detector Full - Wakeup Triggers**

![wld-wakeup-triggers](https://user-images.githubusercontent.com/593900/42602747-435f87c0-8541-11e8-9212-2790f245dfe4.jpg)

**3. BetterBatteryStats - Partial Wakelocks**

![bbs-partial-wakelocks](https://user-images.githubusercontent.com/593900/42602753-48f371ec-8541-11e8-80e5-bb175d7f2466.jpg)

**4. BetterBatteryStats - Alarms**

![bbs-alarms](https://user-images.githubusercontent.com/593900/42602759-505f545a-8541-11e8-928a-a45f795568f9.jpg)

**Comment by tommasoberlose** [comment]
Fixed in version 2.0.1.
