### ISSUE TITLE
UI: Move the GPS privacy notice at the bottom of the screen

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#212]
**Is your feature request related to a problem? Please describe.**
Yes: the text is non-clickable and made me confused when I wanted to select again the Weather Location.
Plus, the text is too long to be in the middle of the screen, it makes UI odd (screenshot 1 in blue).
Plus, the word ''use.'' is alone in a single row, but making the UI with the circlee-info-icon (i) will be okay beacause it makes the text more in the left.

**Describe the solution you'd like**
If GPS activated (like you programmed), display the notice in the bottom of the screen (like for Clock and Glance: screenshot 2 in red).

**Alternative**
Make the notice permanent at the bottom of the screen, but add the text ''When GPS is on, ...''.

![IMG_20201014_005100](https://user-images.githubusercontent.com/64771681/95924532-0725e680-0db8-11eb-8153-dc50f02c6d16.jpg)
![IMG_20201014_005134](https://user-images.githubusercontent.com/64771681/95924533-07be7d00-0db8-11eb-9c2c-87e77c266269.jpg)

**Comment by tommasoberlose** [comment]
I have to change back the UI due to a Google Play Store policy that forces me to show that warning near the "Geolocalization" feature. I'll keep the updated string and increase the font size.

**Comment by Moutony** [comment]
> I have to change back the UI due to a Google Play Store policy that forces me to show that warning near the "Geolocalization" feature. I'll keep the updated string and increase the font size.

Google Weather official app does not display any warning anywhere. So who cares? 😂

**Comment by Moutony** [comment]
I have a new idea: make the GPS notice as a subtitle for Provider section, just like drag-and-drop notice for Glance.
