### ISSUE TITLE
Glance steps number not correct

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#218]
Maybe it is an approximation.
Maybe it also counts few steps from yesterday night.

![Screenshot_2020-10-15-16-03-51-762_com android systemui](https://user-images.githubusercontent.com/64771681/96140411-321b5200-0f00-11eb-8e48-ba9ddd0146e2.jpg)

**Smartphone**
 - Device: Xiaomi Redmi Note 7
 - OS Version: Android 10 with MIUI 11
 - App Version: v2.0.15 (108)

**Comment by tommasoberlose** [comment]
@Moutony I don't really have the control on this, I just request the steps counter to the Google Fit API...
I'm afraid that could happen that there's a little difference.
