### ISSUE TITLE
Missing red message ''this provider needs an API...'' for newcomers

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#219]
**Describe the bug**
I reinstalled the app to see how a newcomer would see the app. I noticed that the red text ''this provider needs an API blablabla...'' was missing (screenshot 1).

**To Reproduce**
1. Go to 'Weather'
2. Click on 'OK'
3. Scroll down to 'Providers'
4. See error.

**Expected behavior**
Display the text for newcomers. Not only when you change providers. 
Explanation: I had to change provider and click again on OpenWeatherMap to see the red texttext (screenshot 2).

**Screenshots**
![IMG_20201015_175041](https://user-images.githubusercontent.com/64771681/96154926-a14c7280-0f0f-11eb-8a4b-764dae6f0676.jpg)
![Screenshot_2020-10-15-17-52-25-660_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96154929-a1e50900-0f0f-11eb-853e-cfa7e57bd837.jpg)

**Smartphone**
 - Device: Xiaomi Redmi Note 7
- OS Version: Android 10
 - App Version: v2.0.15 (108)

**Additional context**
The pop-up message for Weather DOES NOT appear in the bottom of the page like for Clock and Glance when you click on OK. It should appear.

**Comment by tommasoberlose** [comment]
Fixed in the latest beta
