### ISSUE TITLE
Glance & notifications

### ISSUE THREAD

**Issue by tjsuominen** [tommasoberlose/another-widget#224]
**Additional context**
I remember seeing some mention about the "Glance" and "New way of notifications" but I can't find anything related to that in latest release? There's no notifications section in the "Glance" or did I misunderstand?

The way I was secretly hoping to see those was like in the Nokia N9 phone with the Notifications feed:
https://images.app.goo.gl/f4XpMrTgPk1igyCd6

Just thought... :)

**Comment by tommasoberlose** [comment]
@tjsuominen did you check the latest beta version? There's a new glance option to show the last notification arrived on the device. It will be shown just for a brief moment (about 30 seconds) but I'm still working on some details if you'll have any feedback!

**Comment by tjsuominen** [comment]
Sorry, I wasn't having the latest then... Yet, my preferences would be

- show the latest until either dismissed or new one arrives (as an option) < otherwise those will be missed
- show app icon and notification content in a compact way

Will check during the weekend!

**Comment by tommasoberlose** [comment]
I've added an option to change the notification timeout.

**Comment by tjsuominen** [comment]
I have subscribed to the play store beta channel, but I guess you publish the betas only to GitHub, right?

**Comment by tommasoberlose** [comment]
I usually publish a beta version of the app alongside the tag release on GitHub, but the google play store could take a while to accept the new version and publish it to the devices.
