### ISSUE TITLE
Glance Daily steps (former icon, new feature)

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#227]
**Is your feature request related to a problem?**
Former ''Daily steps'' icon (running stickman) was better.
The current icon looks like GPS icon and it is confusing (screenshot 1).
Please go back to former icon (running stickman), but without the black circle because it was too much bold.

**Feature request**
- Change ''Daily steps'' name into ''Fitness'' and integrate ''Heart Pts'' along with ''Steps'' (screenshot 2).
- No more long sentence in widget.
- Only display icon, digit and text: ❤ 16 Heart Pts [big margin] 👟 3689 Steps

**Describe alternatives you've considered**
Why not integrate other third-party Fitness apps (Fitbit, Runastic, Nike...) too?
Let the user choose only 1 app, otherwise it will be too complicated.
But notice that that each app have their own points calculation (Google Fit has Heart Pts and Steps) so adapt your icon, digit and text.

**Additional context**
![Screenshot_2020-10-18-14-41-11-261_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96368117-57070380-1152-11eb-965a-74a824fa80d7.jpg)
![IMG_20201018_144040](https://user-images.githubusercontent.com/64771681/96368118-58383080-1152-11eb-94a6-0b3d1171f577.jpg)

**Comment by LastInLine** [comment]
I definitely agree with the running guy icon being more representative.

**Comment by tommasoberlose** [comment]
The icon now is a heart, because right now the only service supported is Google Fit.
