### ISSUE TITLE
Weather API red text.

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#228]
**Describe the bug**
1. Missing text for newcomers (screenshot 1 and 2)
2. Red text in main page is only in 1 row, where is the second row? (screenshot 3)

**To Reproduce**
1. (Re)install app.
2. Click on 'Weather.
3. Scroll down to 'Providers'

**Expected behavior**
You know. #219 

**Screenshots**
![Screenshot_2020-10-18-15-10-04-871_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96368686-879c6c80-1155-11eb-9ebf-8dc28c1004bf.jpg)
![Screenshot_2020-10-18-15-17-11-392_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96368687-88350300-1155-11eb-8bf4-9756ce2b04c7.jpg)
![Screenshot_2020-10-18-15-15-20-582_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/96368688-88cd9980-1155-11eb-8b96-3ae101d1e60a.jpg)

**Smartphone**
 - Device: Xiaomi Redmi Note 7
 - OS Version: Android 10
 - App Version: v2.0.15 (109)

**Additional context**
Where is the pop-up that explains the user that he must use a third-party provider because Google Awareness is decrepated? It was necessary to explain.

**Comment by tommasoberlose** [comment]
I've removed the Google Awareness warning because I thought it has become deprecated.
I'm developing a new message to explain why a weather provider is needed, but I don't really like those warnings... like the one in the clock tab. I'll think about a new UI and I'll update the tab.

**Comment by Moutony** [comment]
> I don't really like those warnings... like the one in the clock tab. I'll think about a new UI and I'll update the tab.
I understand you. It is redundent with the info text at the bottom of the page. I also think that you can delete all pop-ups (in Clock and Glance). Just keep the info text at the bottom.

**Comment by tommasoberlose** [comment]
@Moutony I've fixed the error display bug and updated the UI. I think that the error messages are currently working fine, what do you think about it? I hope that after this amount of time no one will complain or expect the deprecated Google Awareness option!
