### ISSUE TITLE
Some settings don't refresh widget preview

### ISSUE THREAD

**Issue by Madis0** [tommasoberlose/another-widget#23]
Changing some settings will not instantly refresh the widget preview in app, while the real widget updates fine. I know there is a manual refresh option, but would be nice if they could be fixed regardless. 

- Widget font 
- Text shadow 
- Show clock (that doesn't even update the settings, aka won't show the subsettings instantly) 
- Unit of measure (doesn't even update the real widget instantly)

**Comment by tommasoberlose** [comment]
Hopefully fixed in version 2.0.1.
