### ISSUE TITLE
Event time out

### ISSUE THREAD

**Issue by nolefan32** [tommasoberlose/another-widget#238]
Calendar events stay on the screen door the duration of the event. The stock at a glance times them out after a little while, which is nice for really like events. I keep my work schedule on the calendar, and I don't need to be reminded for eight hours that I need to go to work.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6]
 - OS Version: [e.g. Android 9.0]
 - App Version (that you can find inside the advanced settings) [e.g. v2.0.5 (71)]

**Additional context**

**Comment by Moutony** [comment]
Check your background data settings. Maybe they are disabled for this app. I had the same problem before.

**Comment by tommasoberlose** [comment]
@nolefan32 I think that disabling the battery optimizing could do the trick. Sometimes the OS kills the application in the background, often depends on the device model. Which one do you have?
