### ISSUE TITLE
Weather icon (cloud) not fully visible

### ISSUE THREAD

**Issue by oiiiiiiii** [tommasoberlose/another-widget#240]
![Screenshot_20201026-154521](https://user-images.githubusercontent.com/63345269/97187058-5863ac00-17a2-11eb-9da7-d2bfd8059b5b.jpg)
![IMG_20201026_154658](https://user-images.githubusercontent.com/63345269/97187184-80530f80-17a2-11eb-97f2-f5a32ccf8f0a.jpg)
the cloudy weather is somehow cut off. reducing the font size didn't help. the preview within the app was not bugged however.

**Comment by Moutony** [comment]
Lastest beta version do fix this issue.

**Comment by oiiiiiiii** [comment]
> Lastest beta version do fix this issue.

alright, thank you!

**Comment by tommasoberlose** [comment]
#181
