### ISSUE TITLE
Event shown is not the nearest upcoming

### ISSUE THREAD

**Issue by mrrx7** [tommasoberlose/another-widget#241]
**Describe the bug**
The widget does not show the next upcoming event, but rather the one that is furthest away.

For example: my next upcoming calendar event is tomorrow at 1pm. After that I have another event tomorrow at 5pm. The widget shows the 5pm event, instead of the 1pm event.

**Expected behavior**
I would expect the widget to show my next event (1pm in my example), instead of the one furthest away.

**Smartphone (please complete the following information):**
 - Device: Samsung Note 10+
 - OS Version: Android 10
 - App Version: v2.0.14 (106)

**Comment by Moutony** [comment]
Lastest beta version should have resolved this issue.
