### ISSUE TITLE
Feature Request: Multiple Clocks in Clock Widget

### ISSUE THREAD

**Issue by karanrajpal14** [tommasoberlose/another-widget#243]
**Is your feature request related to a problem? Please describe.**
I currently live away from home on a different time zone and I constantly rely on a clock widget that displays multiple clocks.
Currently, I've found that Google's Clock Widget does a pretty decent job at this and there aren't many aesthetically pleasing widgets that I can use. Would you please consider adding support for multiple clocks in the clock widget similar to Google's widget?

**Describe the solution you'd like**
Addition of a setting that allows adding multiple clocks and allows selecting different cities. Similar to what Google has.
The only improvement from their widget would probably be to improve the layout when only two clocks are present. Currently, Google displays it on the next line instead of the same one which is a waste of space. 

**Describe alternatives you've considered**
I've considered using the stock widget but it's not as feature rich and other clock widgets don't really look as minimalistic as this one.

**Comment by pranavAbe** [comment]
This would be an incredibly useful feature for users like OP and myself who live in different time zones and also need to keep track of times in different parts of the world. Multiple clock support with support for custom naming each clock would be nice too, if presented in a nice layout (preferably, something similar to the Google Clock widget).

**Comment by tommasoberlose** [comment]
Added one addable clock. I don't think to implement real multiple clocks support to keep the widget simple and cleaner.

**Comment by pranavAbe** [comment]
Appreciate the work you've done. If it's no trouble, would it be possible to change the current multiple clock implementation layout to rather one where there's a clock in the green section and another one in the yellow section as roughly annotated in the screenshot below? 

I still believe that a more diverse implementation of multiple clocks would be a great feature to have. I do understand that it might add clunkiness for the average user, but having it as an option for the users who'd prefer it, would be a very welcome addition. 

Again, I very much appreciate that you took note of this issue and implemented the feature but if there was support for at least two clocks, that would help the situation a little more. With the current implementation, it feels like the space around the second clock is being wasted. 

![image](https://user-images.githubusercontent.com/29583966/118372586-145bbb80-b5bb-11eb-9512-940acc2559a0.png)
