### ISSUE TITLE
I know why my alarm is different in the widget

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#246]
**Is your feature request related to a problem? Please describe.**
Yes. The alarm displayed in the widget is never the same as the one i set in my Clock app. 

I have a Xiaomi and I spotted out 2 cases : 
- When the option ''Notification before ringing'' is on (screenshot 1), the Xiaomi's Clock app send a notification 1 hour before the actual alarm time. 
This is why the alarm displayed in the widget was 1 hour before the actual alarm time (screenshot 2). It is logical.

- When this option is off (screenshot 3), the alarm displayed in the widget is 15 minutes before the actual alarm time (screenshot 4). 
I don't understand why... MAYBE the Xiaomi's Clock app send a hidden notification 15 minutes before to the system to activate the alarm and to take the Clock app out of battery saver?

**Describe the solutions you'd like**
**(easy to code and universal to all devices)**
Add an option in the widget to let the user adjust the alarm that is displayed in the widget (image 5).

**Describe alternatives you've considered**
**(hard to code and can lead to more problems depending on device brand)**
Change the way you collect the alarm info. 
Now: i think you collect notifications. 
Future: you will have to collect alarm info depending on each device brand, because it might be coded differently in each Clock app.

**Additional context**
![Screenshot_2020-10-29-11-37-38-066_com android deskclock](https://user-images.githubusercontent.com/64771681/97560097-8df4d900-19de-11eb-8a2e-c8b41f2a5cbf.jpg)
![Screenshot_2020-10-29-11-37-47-907_com miui home](https://user-images.githubusercontent.com/64771681/97560102-8f260600-19de-11eb-89e5-2fb7284bb297.jpg)
![Screenshot_2020-10-29-11-37-01-493_com android deskclock](https://user-images.githubusercontent.com/64771681/97560116-91886000-19de-11eb-85e2-0b50839d0fed.jpg)
![Screenshot_2020-10-29-11-37-25-294_com miui home](https://user-images.githubusercontent.com/64771681/97560775-6fdba880-19df-11eb-8d34-767c72a7f338.jpg)

**Comment by Moutony** [comment]
![Screenshot_2020-10-29-12-15-52-635_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/97563646-a3b8cd00-19e3-11eb-8694-b48c79f955e3.jpg)

**Comment by Moutony** [comment]
![Sans titre](https://user-images.githubusercontent.com/64771681/97788340-81c47380-1bb8-11eb-8348-0d9013f366bf.png)

**Comment by tommasoberlose** [comment]
@Moutony I actually use [this](https://developer.android.com/reference/android/app/AlarmManager.html#getNextAlarmClock()) API to get the next alarm set on the device. I thought about your ideas but I think that would be impossible to check if the information I get is from the API during the option "1h before", "5 minutes before", or when it shows the exact alarm time...
It would be hard just to filter the device ROM.

**Comment by Moutony** [comment]
@tommasoberlose I understand that it is hard to adapt the API to the device ROM.
This is why i suggested to let the user adjust the alarm time himself (last screenshot).

**Comment by tommasoberlose** [comment]
@Moutony that could be a feasible idea if the difference between the correct and the wrong times would always be the same. The user could just adjust that, as you said, but in most cases, this would be the situation:

Device clock alarm set to 8:30
- AW calls the API before 8:10 and gets 8:25 (adjust the alarm to 8:30 with 5 mins of difference)
- AW check the alarm at 8:28 and gets 8:30 (adjust the alarm and shows 8:30)

I can actually access the next alarm without knowing if there are more, this obviously drives me crazy but I can't find an easy solution.

**Comment by Yorshex** [comment]
If I don't have alarms tomorrow, the widget says that it will be at midnight, and the settings say "Alarm clock set by Calendar".

Redmi 8A, Android 10, MIUI 11.
