### ISSUE TITLE
Scalable Font

### ISSUE THREAD

**Issue by morgenman** [tommasoberlose/another-widget#247]
Unlike the implementation on the Pixels (I think), the font does not shrink to accommodate longer amounts of text like calendar entries. This plus the fact that the text doesn't go all the way to the edge of the widget, plus the natural padding that home screens add, means that at a reasonable font size most of my calendar entries have the "...".  

A simple "minimum font size" would do the trick, which would allow the font to shrink to fit information. To get it to function as it is now, just set the font size and minimum to the same value. 

Also, allowing the user to use the full width of the screen for said text would be cool, could be implemented with a padding slider. 

Thank you!

**Comment by tommasoberlose** [comment]
@morgenman I'd really like to be able to do that... believe me!
But the home widgets on Android are based on a very old technology that doesn't give me the possibility to make the font size responsive. I'm barely able to set it.

I don't know if the Google widget is able to do something like that but I think it would be feasible only if wrapped inside the pixel launcher.
