### ISSUE TITLE
Battery percentage

### ISSUE THREAD

**Issue by devindang** [tommasoberlose/another-widget#249]
will another-widget support battery percentage like lawnchair?
![Screenshot_20201110-181239](https://user-images.githubusercontent.com/39517801/98660712-935c0700-2380-11eb-86a3-895498c1caf3.jpg)

**Comment by Nxt3** [comment]
I would also loved if we could show a static battery percentage

**Comment by tommasoberlose** [comment]
I can't show the exact percentage of the battery because the widget is not aware of the battery level change...
Other launchers can show it because they're enabled running foreground and they can register a listener to update a single widget every time the level changes.

**Comment by Nxt3** [comment]
@tommasoberlose Is it possible to display in increments? Like, if my battery is at 78%, could the widget display say, 80%? Or even 75% or 70%?

**Comment by tommasoberlose** [comment]
@Nxt3 I'm afraid not. The available events that I can intercept are these:
`android.intent.action.BATTERY_LOW` fired when the level drops below 15%
`android.intent.action.BATTERY_OKAY`fired when the level rise above the 15%

You could find more about this [here](https://developer.android.com/training/monitoring-device-state/battery-monitoring#MonitorLevel) and [here](https://developer.android.com/reference/android/content/Intent#ACTION_BATTERY_CHANGED).
