### ISSUE TITLE
weather icons clipped

### ISSUE THREAD

**Issue by svxzwn** [tommasoberlose/another-widget#250]
the left side of the icon is cut off. you can move the weather icon and temperature value together a little.

I offer each calendar event on its own line separately. the number of events is equal to the number of lines. notifications of events to be made after the date and weather below.
![Screenshot_20201115-071042](https://user-images.githubusercontent.com/69799148/99161223-c8b27d00-2711-11eb-8cdc-cf75ee1da3b4.png)

**Comment by bkessler33** [comment]
![Screenshot_20201228-121754_Nova Launcher](https://user-images.githubusercontent.com/76706454/103241010-d0676300-4906-11eb-88aa-1272be20a7a6.jpg)

Clipping for me too — although in a slightly different way. Similar to the margin height options already available, divider spacing would be help too.

**Comment by tommasoberlose** [comment]
#181
