### ISSUE TITLE
Move ''Refresh widget'' button to main page (top left corner)

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#251]
It will be more ergonomic. It is a useful button while configuring the widget and when we want to refresh events in the widget (i use this button a lot).

When the user click on the button, display a pop-up text (the same type as for errors) : Widget refresh done.

![IMG_20201124_083039](https://user-images.githubusercontent.com/64771681/100062770-70c1f780-2e30-11eb-849c-0dbf8009942d.jpg)

**Comment by sbs8331** [comment]
As an addendum, I'd like to see an option to refresh the weather by tapping the event or weather.  Thanks.

**Comment by tommasoberlose** [comment]
I've added the options to do nothing and to refresh the widget by tapping on the widget items (events, weather, clock).
As what concerns the refresh icon I've updated the UI to react to any preferences change, without the need to force it.

**Comment by Moutony** [comment]
@tommasoberlose I updated the last version v2.2.2 (120) and i tested what you said.
1. I change the font.
2. I tap on the widget items (events, weather, clock)
3. But the widget doesn't display the new font...
4. I click on Refresh button in menu: it worked.

**Comment by tommasoberlose** [comment]
I've just pushed to the beta channel a new app version (121), let me know if the problem persists.

**Comment by sbs8331** [comment]
Pardon me if this is a dumb question, but I just installed the latest beta version from the play store, and I don't see "the options to do nothing and to refresh the widget by tapping on the widget items (events, weather, clock)." What I see in the "Gestures" setting are the same options as before: default app or choose another app. Am I missing something?  Thanks.

**Comment by tommasoberlose** [comment]
> Pardon me if this is a dumb question, but I just installed the latest beta version from the play store, and I don't see "the options to do nothing and to refresh the widget by tapping on the widget items (events, weather, clock)." What I see in the "Gestures" setting are the same options as before: default app or choose another app. Am I missing something?  Thanks.

#268
