### ISSUE TITLE
Multiple day all-day events

### ISSUE THREAD

**Issue by sbs8331** [tommasoberlose/another-widget#255]
**Describe the bug**
If a Google calendar all-day event spans multiple days, it still shows on the widget even if all-day events are set to be hidden.

**To Reproduce**
1. In Another Widget settings go to settings for Calendar events and turn off all day events.
2. Create an all day event in Google calendar that spans multiple days.
3. Event will show in the set timeframe despite having set all day events to be hidden.

**Expected behavior**
All day event should be hidden.
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto G7 Power
 - Android 10
 - App Version  v2.0.15 (109)

**Additional context**

**Comment by sbs8331** [comment]
I erred somewhat.  It’s not the fact that the all-day entry crosses days that causes the issue.  When setting up an all-day entry in Google Calendar, there is an option to set it up as an “Event” or as an “Out of office” entry, the latter of which will automatically decline meetings scheduled during that period.  It’s that latter entry that causes the widget to show the entry, regardless of whether or not it crosses days.  Apparently this is a somewhat different entry than a normal, or even an all-day, calendar event, and the widget treats it differently, not recognizing it as such.  Thanks.  Apologies for the error.

**Comment by tommasoberlose** [comment]
You're right, the "Out of office" event is not set as "all day".
I've fixed this bug in the latest beta checking the hour of the event.
