### ISSUE TITLE
Personal weather app not listed

### ISSUE THREAD

**Issue by mestar-matt** [tommasoberlose/another-widget#259]
Clicking on the weather started taking me to the Google homepage. When I went to check the app settings, I noticed it would let me choose my weather app of preference (The Weather Network).

 - Device: pixel 5
 - OS Version: Android 11
 - App Version: v2.1.0 (114)

**Comment by mestar-matt** [comment]
Is there no solution too this? Why was my issue closed before anyone
responded to me?

**Comment by tommasoberlose** [comment]
@mestar-matt I'm sorry I didn't comment, I think I've fixed this bug in the latest beta version. Please take a look and let me know.

**Comment by mestar-matt** [comment]
Hi,

Thanks,
Yes, it looks like it is working.

Kind regards,
Matt
