### ISSUE TITLE
The left part of the weather is cut off.

### ISSUE THREAD

**Issue by PGM-Hecate2** [tommasoberlose/another-widget#263]
![Screenshot_20210110-113832](https://user-images.githubusercontent.com/34741149/104113046-1aa20880-5339-11eb-8314-537bb90e8d2b.jpg)

I don't want to turn on the character separator, and I'd like to fix the problem where the left part of the weather is cut off.

**Comment by tommasoberlose** [comment]
@PGM-Hecate2 could you add a screenshot of the typography settings?

**Comment by PGM-Hecate2** [comment]
> @PGM-Hecate2 could you add a screenshot of the typography settings?

![Screenshot_20210111-090738](https://user-images.githubusercontent.com/34741149/104139123-8a250000-53ec-11eb-90aa-fba63d844d18.jpg)
