### ISSUE TITLE
Update UI suggestion

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#265]
Why ? 
- 4 sub-menus are too much.
- A sub-menu with only one item is odd.
- Font ''family'' is an irrelevent name (Google Sans is a font family, but Google Sans - Regular isn't)

Changes suggestions : 
- Move ''Widget font'' item in ''Preferences'' sub-menu.

![IMG_20210110_182948](https://user-images.githubusercontent.com/64771681/104130710-910f2c80-5372-11eb-80ca-b3c3ae687f9e.jpg)

**Comment by tommasoberlose** [comment]
I was thinking about moving the selection of the font style out from the font chooser activity. I actually left the work halfway tho'.

**Comment by tommasoberlose** [comment]
I've moved the option to the preferences section.
