### ISSUE TITLE
Default apps can't change

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#266]
**Describe the bug**
Impossible to change the default apps.

**To Reproduce**
1. Go to 'Gestures'
2. Click on any default app to change settings
3. Select any app

**Smartphone (please complete the following information):**
- App Version: v2.2.2 (120)

**Additional context**
"Calendar" subtitle as default calendar app is not correct because the calendar default app can have different names in one language (exemple in French: Google Agenda, Xiaomi Calendier)

**Comment by tommasoberlose** [comment]
Please check the latest beta version (121), it'll fix the bug, hopefully.
Let me know!

**Comment by sbs8331** [comment]
Apologies for the duplication of this issue.  I'll take a closer look at the open issues list next time.
