### ISSUE TITLE
Refresh (from issue #251)

### ISSUE THREAD

**Issue by sbs8331** [tommasoberlose/another-widget#268]
I left this comment on issue #251, but it was closed so I wasn't sure it would be seen.  If I erred please delete this request: Pardon me if this is a dumb question, but I just installed the latest beta version from the play store (v2.2.2 (120)), and I don't see "the options to do nothing and to refresh the widget by tapping on the widget items (events, weather, clock)" that was noted in issue #251. What I see in the "Gestures" setting are the same options as before: default app or choose another app. Am I missing something? Thanks.

**Comment by tommasoberlose** [comment]
@sbs8331 I think I've added that feature in the latest beta, the number 121.

**Comment by sbs8331** [comment]
Thanks.  I guess 121 hasn't been updated in play store yet.  I'll test when I can install (along with default apps fix raised in other issue).

**Comment by tommasoberlose** [comment]
Be sure to have subscribed to the beta channel!

**Comment by sbs8331** [comment]
I'm listed as a beta tester.  Is there anything else to subscribe to "beta channel"?  Thanks.

**Comment by tommasoberlose** [comment]
No, perfect!

**Comment by sbs8331** [comment]
I just got 121.  When I set the weather tap to refresh, tapping it brings up Google home page on my browser.  When I set calendar to refresh, nothing happens, which I can tell by the icon in the notification section when I refresh from the settings.  It would appear that the refresh function in gestures has a bug.  Thanks.

**Comment by tommasoberlose** [comment]
> I just got v2.2.2 (123). When I set the weather tap to refresh, tapping it brings up Google's home page on my browser.
This is a known problem related to how I open the Google Weather, that it's actually a workaround.

> When I set calendar to refresh, nothing happens, which I can tell by the icon in the notification section when I refresh from the settings.
I've fixed this bug in the latest release (124).
