### ISSUE TITLE
Cannot Change Default Apps

### ISSUE THREAD

**Issue by sbs8331** [tommasoberlose/another-widget#269]
**Describe the bug**
In the Gestures settings, the default apps can't be changed with most recent release v.2.2.2 (120)

**To Reproduce**
1. Open app
2. Click on "Gestures"
3. Under "Default Apps" change setting for Calendar or Weather.
4. New setting isn't accepted, setting shows current default.

**Expected behavior**
Updated default should be accepted.

**Smartphone (please complete the following information):**
 - Device: Moto G7 Power
 - OS Version: Android 10
 - App Version: v2.2.2 (120)

**Comment by tommasoberlose** [comment]
Duplicate #266
