### ISSUE TITLE
Next alarm not showing

### ISSUE THREAD

**Issue by revdeac06** [tommasoberlose/another-widget#272]
On version 2.2.2 using a Pixel 4XL on Android 11, the next alarm on the widget doesn't show and I can't find the option to bring it back. It was there prior to the recent updates (which are nice and appreciated).

**Comment by tommasoberlose** [comment]
@revdeac06 you can find the option to show the next alarm inside the Glance section.
In case you've already enabled the glance provider, could you please share the popup that is shown?
Thank you

**Comment by revdeac06** [comment]
That fixed it, sorry that I didn't see that option.
