### ISSUE TITLE
App crashes while in background

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#276]
**Describe the bug**
![IMG_20210112_173959](https://user-images.githubusercontent.com/64771681/104344334-4f5ebd00-54fd-11eb-8657-ce04f87461f8.jpg)

**To Reproduce**
1. Do nothing
2. See error

**Smartphone (please complete the following inform**
 - Device: Xiaomi Redmi Note 7
 - OS Version: Android 10 with MIUI 12
 - App Version: v2.2.2 (125)

**Comment by tommasoberlose** [comment]
I hope I have fixed this problem in the latest betas. Let me know if the problem persists.

**Comment by Moutony** [comment]
Hi, i think is was fixed. I haven't seen any crash notice since 3 monthes.
