### ISSUE TITLE
Correct Horizontal Spacing

### ISSUE THREAD

**Issue by sbs8331** [tommasoberlose/another-widget#277]
Very minor aesthetic request to correct / reduce the spacing between the conditions icon and the date on its left and temperature on its right.  The attached screenshot shows Another Widget on the top and At a Glance below.  The amount of spacing on the former appear unnecessary.  This can also be seen between the temperature and the following degree symbol and scale. 
Thanks.
![Screenshot_20210112-181027](https://user-images.githubusercontent.com/64859545/104386172-98fdd680-5502-11eb-8938-281d0640121e.png)

**Comment by sbs8331** [comment]
In looking at this again, the issue may be that when text separators are disabled, spaces are left in place rather than the separator just deleted and the surrounding objects moved closer together.

**Comment by Moutony** [comment]
There were no spaces in the previous AnotherWidget versions, even with separator disabled.

**Comment by tommasoberlose** [comment]
Fixed
