### ISSUE TITLE
[FR] Hourly / Daily Weather Info

### ISSUE THREAD

**Issue by tjsuominen** [tommasoberlose/another-widget#279]
**Is your feature request related to a problem? Please describe.**
Not a problem, but extension to functionality.

**Describe the solution you'd like**
Ability to have hourly (or daily) weather info (temperature, symbol) in Smart Content / At a glance (position changeable).

**Describe alternatives you've considered**
Can not use a separate weather widget as the current launcher (Niagara Pro) only allows using one widget at the time.

**Additional context**
See attached image for desired look & feel of the 'component'.

![screen](https://user-images.githubusercontent.com/7660277/104603400-0afe2900-5685-11eb-898c-828ce9b34776.png)

**Comment by sbs8331** [comment]
What I do is to have one of the tap gestures launch a weather app that uses the same service.  If you use Open Weather Map, for example, you could tap to lanuch Open Weather (https://play.google.com/store/apps/details?id=uk.co.openweather), Weawow ([https://play.google.com/store/apps/details?id=com.weawow](url)), or Today (https://play.google.com/store/apps/details?id=mobi.lockdown.weather).

**Comment by tjsuominen** [comment]
Yes, that's what I have and do (with today weather pro), but looking for a feature with Another Widget.

**Comment by sbs8331** [comment]
I'll defer to the developer, of course, but I infer the purpose of Another Widget to be an enhanced version of At a glance, with some additional functionality, rather than featuring multiple layouts / widgets.  Doesn't hurt to make a request, though.

**Comment by tommasoberlose** [comment]
@tjsuominen I have already thought about this feature too! I love the Today Weather widget and there's a similar view in the Google News app too. But as much as I love to add new features to this application I think that a full forecast view doesn't really fit the widget purpose: to give a bunch of useful information at a glance, but not in the detail.
There is also a technical problem: most of the supported weather providers don't allow to access more than one/three days forecast free.

**Comment by tjsuominen** [comment]
Understandable. Thx for clarification.
