### ISSUE TITLE
Alarm clock set by Calendar

### ISSUE THREAD

**Issue by Yorshex** [tommasoberlose/another-widget#281]
The widget displays only today's alarms, in other cases the widget says that the alarm will be at midnight, and the settings say 'Alarm clock set by Calendar'.

I expected the widget to show the nearest alarm clock.

Screenshots:
![](https://user-images.githubusercontent.com/50163030/104818587-501f8800-584a-11eb-9233-3f073fe73811.jpg)
![](https://user-images.githubusercontent.com/50163030/104818590-531a7880-584a-11eb-8159-93ebb0340868.jpg)
![](https://user-images.githubusercontent.com/50163030/104818593-56adff80-584a-11eb-8350-9dcaca1fa45a.jpg)

Smartphone: Xiaomi Redmi 8A
Android version: 10 QKQ.191014.001
App Version: v2.2.2 (127)

Sorry if there are errors in the text.

**Comment by tommasoberlose** [comment]
#158
