### ISSUE TITLE
Unable to manually choose a weather location

### ISSUE THREAD

**Issue by april4352** [tommasoberlose/another-widget#287]
**Describe the bug**
Using yr.no as the weather provider, typing in the location into the search bar, then tapping the search result does nothing. The location is not saved.

**To Reproduce**
1. Go to 'Smart content - Weather - Location'
2. Type a location name into the search bar
3. Tap the search result and watch nothing happen. The location does not get saved.

**Expected behavior**
Tapping the search result should save it as the preferred weather location.

**Screenshots**
![Screenshot_2021-01-29-08-10-29-767_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/78192974/106234274-90e3ad80-6209-11eb-8cd3-64d32eb16c1d.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Poco X3 NFC
 - OS Version: Android 10
 - App Version: 2.2.2 (128)

**Additional notes**
Unable to test other weather providers as I don't have any required accounts.

**Comment by Avinash-Dwivedi** [comment]
Same issue here as well was about to report :)

**Comment by tommasoberlose** [comment]
Fixed
