### ISSUE TITLE
Feature request: Option to change alignment of text in widget

### ISSUE THREAD

**Issue by gokulsoumya** [tommasoberlose/another-widget#289]
Currently the text in both the rows is centered and there is no way to change the alignment. I noticed this when using the widgets with Niagara launcher. The clock and the apps list are left aligned and the widget looks out of place being centered. An option to change the alignment either per row or as a whole would be helpful.

P.S. Really love the design of the app and the glance feature ;)

**Comment by tommasoberlose** [comment]
Feature implemented.
