### ISSUE TITLE
Clock Font

### ISSUE THREAD

**Issue by snooz3r** [tommasoberlose/another-widget#290]
![Screenshot_20210202-112841](https://user-images.githubusercontent.com/13352330/106638961-0d4bf880-654a-11eb-9991-5d68015f9c1d.png)
The font of the clock is persistent and doesn't change even when you change the widget font.

**Comment by sbs8331** [comment]
I don't use the clock but was playing around with it.  One suggestion I have it to have the text shadow setting apply to the clock as well as to the date/weather.  It seems to look inconsistent to have it for one and not the other.
![Screenshot_20210202-113343](https://user-images.githubusercontent.com/64859545/106631450-c90d2800-654a-11eb-8a4d-7655597b4da3.png)

**Comment by snooz3r** [comment]
> I don't use the clock but was playing around with it. One suggestion I have it to have the text shadow setting apply to the clock as well as to the date/weather. It seems to look inconsistent to have it for one and not the other.
> ![Screenshot_20210202-113343](https://user-images.githubusercontent.com/64859545/106631450-c90d2800-654a-11eb-8a4d-7655597b4da3.png)

is it not possible to change the clock font at all?

**Comment by tommasoberlose** [comment]
#306
