### ISSUE TITLE
Alarmas con 1 hora de retraso

### ISSUE THREAD

**Issue by aritzvinagre** [tommasoberlose/another-widget#294]
Hola, tengo un Blackshark 3 con S.O. joyui 11(basado en miui 11). 

Cuando pongo una alarma en la aplicación nativa de reloj, en el widget siempre me sale con 1 hora de retraso. Es decir si está puesta a las 9:00am, en el widget sale alarma a las 8:00.  Ya me he acostumbrado, pero me gustaría que saliese la hora correcta. He probado de todo. El móvil está con la región correcta y la hora el móvil la muestra correctamente. Adjunto capturas. Gracias. 
![Screenshot_2021-02-20-10-30-51-518_com android deskclock](https://user-images.githubusercontent.com/74631933/108591003-bb3b0d80-7366-11eb-8ce0-e68ad2df5623.jpg)
![Screenshot_2021-02-20-10-30-47-240_com teslacoilsw launcher](https://user-images.githubusercontent.com/74631933/108591008-bfffc180-7366-11eb-85ad-262e70d40974.jpg)

**Comment by tommasoberlose** [comment]
#246
