### ISSUE TITLE
Feature Request: More update frequency options

### ISSUE THREAD

**Issue by DankGroundhog** [tommasoberlose/another-widget#297]
I love this widget alot and all but I wish there were more refresh options for the weather. That would be all. I would include further optimization, but I know you guys are up to that anyways. Thanks for the great app. Cheers.

Phone: Samsung A71

**Comment by sbs8331** [comment]
I'm not sure I've seen any other widgets that have more refresh frequency options as does this one. 
As a workaround You can use the Gestures setting to refresh manually by tapping the widget's temperature.

**Comment by tommasoberlose** [comment]
The current weather refresh options are balanced on the need of updating the weather in short time periods and the further battery drain.
