### ISSUE TITLE
Weather icon packs

### ISSUE THREAD

**Issue by AxiK101** [tommasoberlose/another-widget#298]
Can you add compatibility for Chronus's weather icon packs? Also in the inbuild icons there's no option to add shadow behind them, only for the text. 😊

A third row for notifications info would be nice too.

**Comment by tommasoberlose** [comment]
Another Widget doesn't currently support external icon packs because I want to keep that feature simple and usable.
As for the other features I prefer the widget clean and without too much stuff visible at the same time.
