### ISSUE TITLE
[Question] Another Widget icon similar to registered trademark Cirrus® under Mastercard

### ISSUE THREAD

**Issue by aaronhatesregex** [tommasoberlose/another-widget#301]
**Is your request related to a problem? Please describe.**
From [the source code](https://github.com/tommasoberlose/another-widget/blob/main/app/src/main/ic_launcher-playstore.png) and Play Store page thumbnail, it looks like the app icon is similar to [Cirrus](https://en.wikipedia.org/wiki/Cirrus_(interbank_network)) which according to Wikipedia is a subsidiary of Mastercard. And on [More About Our Brands](https://brand.mastercard.com/brandcenter/more-about-our-brands.html) page on Mastercard, Cirrus® shows up with a registered trademark symbol. *Maybe* there is certain risk to use that icon?

**Describe the solution you'd like**
Change the app icon and notify the change to end users in an appropriate way.

**Describe alternatives you've considered**
Evaluate the legal risks and if it's fine to use it, just leave it as it was.

**Additional context**
I'm not a lawyer so maybe I'm just making a fuss and obviously Google already approves the app on Play Store...

**Comment by tommasoberlose** [comment]
@aaronhatesregex thank you for sharing this. I honestly haven't seen that icon before but you're right in saying that is quite similar to the AW icon. Which has been created by me playing around with shapes and colors without a specific design in mind.

Anyway, I think that the AW icon is not an important brand for the application and is not commonly known so there will probably not be any problem.

**Comment by Moutony** [comment]
I think you can change the current circle shape by a triangle shape🔻. The two mixed triangles will form the W letter (stands for Widget).
