### ISSUE TITLE
Weather provider

### ISSUE THREAD

**Issue by Delmi26** [tommasoberlose/another-widget#302]
Please add AccuWeather to the weather provider, because the available weather provider is not working well at my place.

**Comment by sbs8331** [comment]
AccuWeather is expensive.  The developer likely needs to hold down costs.  There are five providers available for Another Widget.  Are you saying that none of them work at your place?

**Comment by tommasoberlose** [comment]
Most of all, AccuWeather has a limited number of requests available in the freemium accounts.
That would be a problem with high weather refresh frequencies.

I hope one of the other providers would be reliable enough.
