### ISSUE TITLE
Weather doesn't work on my Oneplus8 Android 11 device

### ISSUE THREAD

**Issue by devindang** [tommasoberlose/another-widget#303]
**Describe the bug**
Even if I fill in the API key, it will not remind me that I have configured it correctly, and the progress bar is endlessly in progress, weather information is also not displayed in the widget. It used to work well on Android 10

**To Reproduce**
1. Go to 'Weather'
2. Click on 'Weather provider'
3. Click on Setting icon behind any provider
4. Fill in API key
5. See the error

**Expected behavior**
It should work well.
**Screenshots**

**Smartphone (please complete the following information): **
 - Device: [OnePlus 8]
 - OS Version: [Android 11.0]
 - App Version  [v2.2.2]

**Additional context**
None here.

**Comment by devindang** [comment]
Thank you. bug fixed

**Comment by CerberusCode** [comment]
I have same issue, how did it fixed?
