### ISSUE TITLE
Weather as at-a-glance

### ISSUE THREAD

**Issue by Madis0** [tommasoberlose/another-widget#310]
**Is your feature request related to a problem? Please describe.**
The weather could also be one of the things that appear only when nothing more important comes up.

**Describe the solution you'd like**
A weather option under the "at a glance" menu.

**Describe alternatives you've considered**
Simply allow displaying weather on a separate row

**Additional context**
N/A

**Comment by tommasoberlose** [comment]
Hi, the weather feature is based on multiple weather providers that provide different kinds of information. So showing the weather on a dedicated row would be difficult considering that it would need more information shown.

**Comment by Moutony** [comment]
I think he meant that you can make Weather as an 'At a glance' option like you did for the Events (toggle-on it will display the weather only on the second row)
