### ISSUE TITLE
[UI update] Default background for widget preview

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#322]
**Current:**
When I select white (pic 1) or light/pale (pic 2) colors, the background is blue.
When I select dark colors (pic 3), the background turns white.

**Suggestion:**
When I select dark colors, the background turns into lighter/pastel blue.

![Screenshot_2021-05-12-18-35-43-040_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/118013528-81b8e380-b352-11eb-8217-5ff0095c9933.jpg)
![Screenshot_2021-05-12-18-35-48-060_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/118013537-82517a00-b352-11eb-870d-97322ad8de69.jpg)
![Screenshot_2021-05-12-18-35-53-829_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/118013538-82517a00-b352-11eb-971b-b9fc9c2352b8.jpg)

**Comment by tommasoberlose** [comment]
The background of the preview was based on the main color, if dark or not.
But the result is not that good tho' so I fixed it to the accent color (light blue).

**Comment by Moutony** [comment]
Yes the accent color background was a great choice.
But i think you can also fix the background for dark text into pastel blue (instead of pure white) :
- #FFE3F2FD (lightest blue)
- or #FFBBDEFB (lighter blue)
- or #FFE1F5FE (lightest blue 2)
- or #FFB3E5FC (lighter blue 2)

**Comment by tommasoberlose** [comment]
Now that I've thought about it, keeping just one color is the best choice: if someone is in need of having a text color that is not visible on the accent color he should just show the wallpaper.
