### ISSUE TITLE
[UI issue] Widget preview height extends when Text aligment is set on Left/Right

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#325]
**Expected behaviour**
The widget preview height still the same wether we select Center of Left/Right.

Btw #317 issue has been correctly fixed, if you ask :)

![Screenshot_2021-05-13-09-16-09-828_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/118092549-89b56980-b3cc-11eb-867d-fca5ddf467d4.jpg)
![Screenshot_2021-05-13-09-16-19-599_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/118092553-8ae69680-b3cc-11eb-968a-3338f8a88a9d.jpg)

**Comment by tommasoberlose** [comment]
It's something needed due to the bigger height the widget has with the weather on another row.

**Comment by Moutony** [comment]
Idk how your code language works but i think it is only UI, so you can still force the height and add hide-overflow, imma right?

**Comment by Moutony** [comment]
My bad: i didn't see that the weather was moved on another row. I understand now why you extented the preview height. 
Btw it's a little bit odd, since i was used to see the widget with only 2 rows, not 3 haha
