### ISSUE TITLE
Change 1st column with 2nd column 

### ISSUE THREAD

**Issue by Yabadabadooooo** [tommasoberlose/another-widget#373]
**Describe the bug**
I know there was a button to change that. I've been now looking for this button for about 1 hour and i couldnt find it. 
Could somebody pls help me? 

Thank you 

**Screenshots**
![Screenshot_20211214-135244](https://user-images.githubusercontent.com/85934117/146001919-a148ef7d-290f-4bcb-bcba-7d304e397dea.png)

**Smartphone (please complete the following information):**
 - Device: [pixel 5 ]
 - OS: [e.g. Android 12]
 - App Version: latest 2.3.3. (139)

**Additional context**

**Comment by Yabadabadooooo** [comment]
Got it

**Comment by Parth-Mawai** [comment]
> Got it

can you help me with this as i can't find it

**Comment by Yabadabadooooo** [comment]
> 

![Screenshot_20220314-134347](https://user-images.githubusercontent.com/85934117/158174772-f75b01ce-567a-4435-ae77-c350f03ee71f.png)
