### ISSUE TITLE
All at-a-glance options are "hidden"

### ISSUE THREAD

**Issue by vawalker** [tommasoberlose/another-widget#381]
**Describe the bug**
Widget never shows any at-a-glance information. Settings show all glance options as "hidden".

**Troubleshooting**
- confirmed that requested permissions are enabled
- temporarily unchecked all calendars to ensure no events

**Screenshots**
![Screenshot_20220225-215833](https://user-images.githubusercontent.com/21223019/155826435-2f61fc86-756e-421c-ae27-95299f247b3f.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS Version: Android 12 (build: SQ1D.220205.004)
 - App Version: 2.3.3

**Additional context**
- launcher used is Nova

**Comment by mukhtartehrani** [comment]
You can click on individual choice and enable it
