### ISSUE TITLE
Can't resize vertically 

### ISSUE THREAD

**Issue by ghost** [tommasoberlose/another-widget#39]
Can't resize vertically after the last update ( 1.3.1)

Any help to solve this?
![Screenshot_20191117-230156](https://user-images.githubusercontent.com/57878278/69015685-50926980-098e-11ea-8d09-0a037f2b36e7.jpg)
![Screenshot_20191117-230148](https://user-images.githubusercontent.com/57878278/69015686-512b0000-098e-11ea-9287-4f59618c6633.jpg)

**Comment by tommasoberlose** [comment]
Hopefully fixed in version 2.0.1.
