### ISSUE TITLE
[Bug] Text gets cut on the bottom

### ISSUE THREAD

**Issue by jonyroda97** [tommasoberlose/another-widget#42]
S20 Ultra, 5x2 Widget gets cut on the bottom but supposedly has space to show.

![Screenshot_20200504-073354_One UI Home](https://user-images.githubusercontent.com/8282833/80941174-a3939800-8dd9-11ea-8902-63a7153df492.jpg)

**Comment by tommasoberlose** [comment]
I'll publish a new beta version of the app with a few fixes. Let me know if that fixes your problem.

**Comment by edimistra** [comment]
I can see the same bug with the Samsung Galaxy Note 10+ as well

**Comment by tommasoberlose** [comment]
I've just published the beta version v2.0.5.
Let me know if you have the chance to try it and check if the bug persists.

**Comment by edimistra** [comment]
Hi @tommasoberlose I can still see the cut off, 8 forgot to mention that it happens when I extend the widget to 5x1. In 4x1 looks good

**Comment by tommasoberlose** [comment]
@edimistra is the cutoff present in the application too?

**Comment by edimistra** [comment]
No, it looks good in the app @tommasoberlose

**Comment by edimistra** [comment]
![Screenshot_20200504-150057_Another Widget](https://user-images.githubusercontent.com/17056693/81002985-20456700-8e18-11ea-8507-e426505cffc6.jpg)
![Screenshot_20200504-150026_One UI Home](https://user-images.githubusercontent.com/17056693/81002995-24718480-8e18-11ea-9a5f-3ef67e8765d5.jpg)

**Comment by tbmny** [comment]
The update really fixed everything for me.

![1588619483530](https://user-images.githubusercontent.com/24422506/81003913-94ccd580-8e19-11ea-9d46-71a80deb83b2.png)

![1588619491405](https://user-images.githubusercontent.com/24422506/81003930-9b5b4d00-8e19-11ea-85c2-475eb61b6be8.png)

**Comment by jonyroda97** [comment]
2.0.5 fixed it for me. S20 Ultra

**Comment by tommasoberlose** [comment]
Great! Thank you guys!
