### ISSUE TITLE
Widget doesn't appear / disappears

### ISSUE THREAD

**Issue by MJ8260** [tommasoberlose/another-widget#43]
At first it didn't show the actual info, only "uploading widget" without anything ever uploading and now, after clearing cache, it just disappears from home screen.

**Comment by tommasoberlose** [comment]
@MJ8260 are you able to see the updated widget inside the application?

**Comment by MJ8260** [comment]
Hi @tommasoberlose.
I can...it only disappears when I try adding it to the home screen (I've got a Moto g6 plus and I'm using go launcher if that helps).
Thank you!

**Comment by tommasoberlose** [comment]
Is the widget on the screen? Can you resize it for example?

**Comment by MJ8260** [comment]
I only know it's there because if I want to retry adding it there's no room and I can drag it but there's nothing there.

**Comment by tommasoberlose** [comment]
Please try to select a custom application to open the calendar, the event, the weather and the clock. Let me know

**Comment by MJ8260** [comment]
Still nothing
![Screenshot_20200504-132801](https://user-images.githubusercontent.com/64771208/80965914-4e707a00-8e0b-11ea-891d-7e12aa1219b7.png)

**Comment by tommasoberlose** [comment]
That's odd. I'm not able to reproduce your problem right now, but I've just published the beta version v2.0.5. Let me know if you have the chance to try it and check if the bug persists.

**Comment by MJ8260** [comment]
It's probably my problem all along...I'll keep trying!
Thank you so much for your help!
