### ISSUE TITLE
Next alarm display is wrong

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#45]
I set no alarm on my phone. But the widget displays an 5:10 alarm...
When I set an alarm on my phone (8:00), the widget still displays 5:10...

**Comment by Moutony** [comment]
When I set an alarm on my phone (8:00), the widget still displays 5:10...

**Comment by tommasoberlose** [comment]
Hei @Moutony, it seems that could be a system error.
Could you please check if the alarm is set just a few minutes after your actual time?

Thanks

**Comment by Moutony** [comment]
No, the alarm is not set few minutes after my actual time. 
It is weird because the alarm indicator in the widget is at a time in the middle of the night without any logic. I tested the widget in the afternoon.
Plus, the widget didn't asked permission to access my Clock app, so it will never be able to know my alarms ahaha

**Comment by davidfguillaume** [comment]
I have a similar issue, my alarm is set for 7am but the widget shows it at 6:55

**Comment by tommasoberlose** [comment]
If the widget displays a wrong alarm is because some third-part app set the alarm to update itself. This is a known bug but it is independent of my application.
In the new beta version of the app you could check which app is setting the wrong alarm. You'll need to uninstall it to see the right alarm.

**Comment by davidfguillaume** [comment]
The widget still displays the alarm incorrectly in the beta, I have long pressed and it says the alarm is set by clock
![Screenshot_20200506-202203_Another Widget](https://user-images.githubusercontent.com/64869794/81219270-77de0100-8fd7-11ea-8ed2-e6559bd6c3b3.jpg)
![Screenshot_20200506-202215_Clock](https://user-images.githubusercontent.com/64869794/81219276-7b718800-8fd7-11ea-8a60-24cd40696cf7.jpg)

**Comment by tommasoberlose** [comment]
@davidfguillaume I honestly don't know what to say because I can't handle the next alarm, I just check the AlarmManager component and, if the alarm seems wrong, I show a warning to the user. If the app that set the alarm is the default clock app you can just try to update the widget from the app and see if the next alarm updates.

**Comment by davidfguillaume** [comment]
it is now showing the alarm @ 19:30 with the latest beta 2.0.5

**Comment by tommasoberlose** [comment]
> it is now showing the alarm @ 19:30 with the latest beta 2.0.5

Is that the right time? Is the problem persisting?

**Comment by Moutony** [comment]
Hi, the new version (published today) shows the correct alarm...
BUT it isn't optimised for summer/winter hour (like we have in France)

**Comment by tommasoberlose** [comment]
> Hi, the new version (published today) shows the correct alarm...
> BUT it isn't optimised for summer/winter hour (like we have in France)

I live in Italy and my device shows the right alarm, could you please share a screenshot of the widget and the clock app? Thanks

**Comment by davidfguillaume** [comment]
It still shows my alarm 5 minutes early what ever time I set it for, I have Samsung Galaxy S20 with Android 10 if that helps, I can also share the debug logs if you would like

**Comment by Moutony** [comment]
> > Hi, the new version (published today) shows the correct alarm...
> > BUT it isn't optimised for summer/winter hour (like we have in France)
> 
> I live in Italy and my device shows the right alarm, could you please share a screenshot of the widget and the clock app? Thanks

![Screenshot_2020-05-09-22-38-03-423_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/81484461-ddcfc000-9245-11ea-8e98-bf941038404b.jpg)
![Screenshot_2020-05-09-22-37-57-609_com android deskclock](https://user-images.githubusercontent.com/64771681/81484462-df00ed00-9245-11ea-83d0-2b950a431761.jpg)

**Comment by tommasoberlose** [comment]
Thanks, I'll look into it.

**Comment by Moutony** [comment]
I found another weird thing today: it was 10:27 and the next displayed alarm was 19:27 while I didn't set enything like that... I think the widget sometimes pick the actual time and add some hours as the alarm.

PS: Now it is 10:32 and the widget still shows an alarm at 19:27


![Screenshot_2020-05-10-10-27-47-890_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/81494446-48feae00-92a9-11ea-8bae-4d64fa79540e.jpg)
![Screenshot_2020-05-10-10-27-59-984_com android deskclock](https://user-images.githubusercontent.com/64771681/81494447-49974480-92a9-11ea-8dfe-263044b9e47b.jpg)

**Comment by Moutony** [comment]
I think I figured out where the problem comes from: my phone doesn't have a ''Default clock app''. 


When my option ''Tap on clock opens'' is set on ''Default clock app'', nothing happens when I tap on the widget: I have to manually pick an app.

I think you can solve the Alarm issue by making the user manually select the alarm provider app.

![IMG_20200510_104056](https://user-images.githubusercontent.com/64771681/81494759-7c423c80-92ab-11ea-9215-e944dca7b122.jpg)
