### ISSUE TITLE
Clock does not respond on click

### ISSUE THREAD

**Issue by jensen-me** [tommasoberlose/another-widget#46]
After trying several times. Changing clock in settings does nothing. No reaction at all
My device is Oneplus 7 with Android 10.

**Comment by Moutony** [comment]
You must set an app (of your phone) in the 'Tap on clock opens' menu

**Comment by jensen-me** [comment]
Have tryed both set app to clock and defalt. Non of these work

hilsen Bjørn.
Sendt fra Android

man. 4. mai 2020, 12:01 skrev Moutony <notifications@github.com>:

**Comment by jensen-me** [comment]
Uninstall, clean and install again. Then choose Klokke, as app. Have tryed this before, and it seems like the new setting didn't save. I must jump a bit around in the app, before it saves the new settings. Now it works
