### ISSUE TITLE
Unable to see weather even inside app when enabled

### ISSUE THREAD

**Issue by siddvank** [tommasoberlose/another-widget#48]
I am using oneplus 5t with android P

**Comment by siddvank** [comment]
![Screenshot_20200504-190607](https://user-images.githubusercontent.com/64788618/80971412-5dbaec00-8e3a-11ea-9260-39bc3637ac00.jpg)

**Comment by tommasoberlose** [comment]
When did you create the OpenWeather API key? 
It could need 15/20 minutes to the key to be activated.

**Comment by siddvank** [comment]
I signedin to openweathermap and took the api key more than an hour ago

**Comment by siddvank** [comment]
Sorry. Its working fine :)
