### ISSUE TITLE
Spacing between the clock and calendar info

### ISSUE THREAD

**Issue by doopsy4** [tommasoberlose/another-widget#50]
Would it be possible to add a toggle/slider for the amount of spacing between the clock and the calendar info? At the moment there's way too much space and it doesn't look right.

In addition, the widget preview in the app doesn't match what it looks like. The preview shows less spacing than the actual widget and I don't see an option within the app to change it.

![Screenshot_20200504-112159](https://user-images.githubusercontent.com/64794763/80982631-9686a100-8df9-11ea-94d8-1e4737392c2d.png)
![Screenshot_20200504-112040](https://user-images.githubusercontent.com/64794763/80982635-971f3780-8df9-11ea-833b-6fb84ec56dfc.png)

**Comment by tommasoberlose** [comment]
@doopsy4 I'll add this feature in the release v2.0.5-beta02.
