### ISSUE TITLE
ability to shade background

### ISSUE THREAD

**Issue by lmb02** [tommasoberlose/another-widget#52]
My wallpaper changes every hour (photos) and the widget font sometimes matches the wallpaper.  While shading text can help a bit, it would be nice to be able to select a degree of shading the background of the widget itself. With shading the background of the widget the wallpaper is still visible but can contrast with the widget text to make said text visible no matter what the wallpaper is.

**Comment by tommasoberlose** [comment]
I've just checked and it's not possible to be notified when the wallpaper changes.
Which app are you using?

**Comment by lmb02** [comment]
Hello again,
I was wondering if the "Show Wallpaper" command, with choices of "Visible" and "Hidden" might be intended to do what I want.
If so, please be advised that on Samsung S10+ from Verizon in the US, on the latest updates, using the Nova Launcher Prime v6.2.12 UI rather than Samsung UI, the "Show Wallpaper" command does not appear to do anything.
If "Show Wallpaper" is supposed to do what I'm asking for, then perhaps being able to set the degree of transparency and the colour would be helpful.  In fact, wasn't that available in the prior version of your app?
Thank you for making this app available and working to make it even better.

Michael

---------------
"We're all stories in the end.  Just make it a good one, eh?"
 

    On Monday, May 4, 2020, 5:28:43 PM PDT, michael.butler <michael.butler@sbcglobal.net> wrote:  
 
 Hello,
Thank you for the quick response.
I use wallpaper changer, but that's irrelevant to the request.
What I thought I was asking was the ability to select a background shading for the screen area of just the widget and being able to define the percentage of transparency of the wallpaper thru the widget background.
Having your app adjusting to the wallpaper colours dynamically would seem to require quite a lot of work on your part compared to doing something like overlaying the area occupied by the widget with a shade of grey (or user selectable colour) allowing XX% transparency to the wallpaper underneath would be easier.  The background would provide the contrast to the text of the widget.
Many thanks for providing a really great widget.
Regards,
Michael
----------------------------"It stands to reason. I've never understood that. It sits to reason sounds much more comfortable."

-------- Original message --------From: Tommaso Berlose <notifications@github.com> Date: 5/4/20 16:34 (GMT-08:00) To: tommasoberlose/another-widget <another-widget@noreply.github.com> Cc: lmb02 <Michael.butler@sbcglobal.net>, Author <author@noreply.github.com> Subject: Re: [tommasoberlose/another-widget] ability to shade background (#52) 



I've just checked and it's not possible to be notified when the wallpaper changes.
Which app are you using?

**Comment by tommasoberlose** [comment]
The "show wallpaper" feature enables the launcher wallpaper inside the preview in the application.
You can set a background in the widget with the newest update of the beta version of the app.
