### ISSUE TITLE
Second line is horizontally cut off when widget size is 5x1

### ISSUE THREAD

**Issue by pratnala** [tommasoberlose/another-widget#55]
It looks fine in 4x1 but my home screen is 5 units wide. Would like it to be in 5x1. This issue wasn't there in the previous version.

Device: Samsung Galaxy S20 Ultra
Software: Android 10 running Another Widget v2.0.4, One UI 2.1

Screenshot: 
![image](https://user-images.githubusercontent.com/1689565/81027742-afac4380-8e33-11ea-8c61-d01a56fe9b28.png)

**Comment by tommasoberlose** [comment]
Hi, that seems to be an issue that occurs only on Samsung devices.
I'm not able to reproduce the error on my own device, but I published a beta version of the app that seems to fix the bug. Please let me know if you have the chance to try it.
Thanks

**Comment by tommasoberlose** [comment]
You can refer to #42 if your problem persists.

**Comment by pratnala** [comment]
Where's the beta?
