### ISSUE TITLE
Weather won't show up

### ISSUE THREAD

**Issue by LukeHunter19** [tommasoberlose/another-widget#57]
I've followed all of the instructions on the app, but I cannot get the weather info to show up when I create the widget or even in the preview.

**Comment by hmilgraum** [comment]
Same problem here

**Comment by tommasoberlose** [comment]
Hi, the API key could take 10/20 minutes to be enabled.
Do you have the location enabled or did you enter a custom address?

**Comment by hmilgraum** [comment]
Location enabled
And I waited 24 hrs for the API key...
Thanks though
________________________________

**Comment by tommasoberlose** [comment]
Does the weather update when you open the app? Do you have the last beta version of the app?

**Comment by zayebystymis** [comment]
> Does the weather update when you open the app? Do you have the last beta version of the app?

No, weather is not updating at all if there is used location. I cannot even force it with change of temperature unit, just changing location to defined city is causing update

**Comment by tommasoberlose** [comment]
> > Does the weather update when you open the app? Do you have the last beta version of the app?
> 
> No, weather is not updating at all if there is used location. I cannot even force it with change of temperature unit, just changing location to defined city is causing update
> 
> Yes, I'm having recent beta version.

@zayebystymis could you please tell which device and Android version are you using?

**Comment by leoyinjou** [comment]
> > Does the weather update when you open the app? Do you have the last beta version of the app?
> 
> No, weather is not updating at all if there is used location. I cannot even force it with change of temperature unit, just changing location to defined city is causing update
> 
> Yes, I'm having recent beta version.

I first had that problem when my OnePlus 7 Pro running Android 10 OxygenOS 10.0.5 prompted me to allow location (only when app is in use, no "always on" option during first popup) when turning on Weather in widget. After the previous update about 24hrs ago, i went into app details > permissions > location to set it "always on" instead of "on when app is in use only" and seemed to fix this.
Not sure if it is permission issue or retriggering permission update after app update solved the problem. @tommasoberlose you have any comments?

**Comment by hmilgraum** [comment]
> Does the weather update when you open the app? Do you have the last beta version of the app?

I have the latest beta (from Google play as of today), tried both enabling geolocation and choosing a city, revoked and reinstituted location permission (all the time).... Still, weather doesn't show up, even in the preview.
I am running Android 10 on a Samsung S10e.
Thanks

**Comment by zayebystymis** [comment]
> @zayebystymis could you please tell which device and Android version are you using?
 @tommasoberlose LG V60 with Android 10

**Comment by zayebystymis** [comment]
After current reinstall due to huge memory usage #76, now weather service is working fine. But I needed to manually allow for location (no popup for access to permission)

**Comment by tommasoberlose** [comment]
I'll check the weather update when the GPS location is required. I'll keep you posted

**Comment by thinkgadgetsme** [comment]
Weather does not update on my OnePlus 6t automatically. I have setup the update frequency to 1 hour but that doesn't happen. I have to open the app and go back to home to force the weather update.

**Comment by tolrm** [comment]
On my OnePlus 8 Pro I had the same until I locked the app, so that it stays active in the background (i.e. it cannot be killed from recents). Also I set Android to not optimize for battery usage for this app.

**Comment by tommasoberlose** [comment]
@tolrm @thinkgadgetsme Did you grant the background location permission to the app?

**Comment by thinkgadgetsme** [comment]
I see the weather information is updated properly after the last app update. It is no longer an issue.

**Comment by tommasoberlose** [comment]
Perfect!

**Comment by hmilgraum** [comment]
Weather still not showing up for me at all.... Tried reinstalling, tried latest beta, tried getting a new api key, manually granting location access, tried entering a location instead..... No change.
