### ISSUE TITLE
Alarm not needed

### ISSUE THREAD

**Issue by PegaloShield** [tommasoberlose/another-widget#58]
Can you make an option to get rid of the alarm? I personally don't use my phone alarm; I use my smartwatch for that. The placeholder alarm of 11:59 AM isn't needed either. Thanks.

**Comment by vishrutkmr7** [comment]
Yes, even though there is an alarm set, it's not required to show up on the widget... There should be a toggle to enable/disable it for someone who may need it.

**Comment by vishrutkmr7** [comment]
![Screenshot_20200505-114233](https://user-images.githubusercontent.com/12652202/81039047-918f2380-8ec5-11ea-9cc4-a01aae6c1f7b.jpg)
To hide the alarm... On the clock tab (as seen in the screenshot above) enable the clock and then set the "Show next alarm when possible" as `Hidden`

**Comment by tommasoberlose** [comment]
You can hide the next alarm from the Clock settings (in the new updates the option will be enabled even with the clock hidden).
