### ISSUE TITLE
Weather not updated with usage of geo location

### ISSUE THREAD

**Issue by zayebystymis** [tommasoberlose/another-widget#60]
Even with recent update regarding permission there is no visible weather. When it's set manually then it's visible, but after change to geo location is not updating anymore.

Happened on Android 10

**Comment by tommasoberlose** [comment]
Hi @zayebystymis, check #57

**Comment by zayebystymis** [comment]
This is not the problem, my api key is valid for months. Like I said, when manually selected location, than weather is updated and visible. But when I switch to "geo location" there is no updates anymore. With new configuration (clear app data) when geo location is set there is no weather at all. Please reopen and fix.

**Comment by zayebystymis** [comment]
For me it seems like app is not asking for location at all. It's not showing on list of apps using location service. For me right now just manual location is working fine

**Comment by Moutony** [comment]
Same, the app don't ask for GPS permission so I had to enter my city instead to using GPS. 
It works with custom city.

**Comment by tommasoberlose** [comment]
Just refer to the #57, please.
I'll try to dig into this problem asap and I'll let you know any update on the other issue.
