### ISSUE TITLE
Need line spacing setting

### ISSUE THREAD

**Issue by madmiike** [tommasoberlose/another-widget#64]
If you could adjust line spacing in this it would be perfection! 
![Screenshot_20200505-094349_Nova Launcher](https://user-images.githubusercontent.com/64857897/81092245-2fc6bd80-8eb5-11ea-935c-38c71e2a129a.jpg)

**Comment by tommasoberlose** [comment]
Please try the beta version of the app and let me know if the problem persists.
Thanks

**Comment by oxydeon** [comment]
Perfect for me with beta. Thank you!
