### ISSUE TITLE
Music player request

### ISSUE THREAD

**Issue by Dhrubaof2002** [tommasoberlose/another-widget#68]
Add auto colour option based on wallpaper in text colour section between black and white colour .

**Comment by BracesForImpact** [comment]
Show current music in media player (YouTube Music in this case) in widget.

**Comment by tommasoberlose** [comment]
> Add auto colour option based on wallpaper in text colour section between black and white colour .

Please refer to #52, it's not possible to update the widget when the wallpaper changes, you'll need to update on your own every time.

**Comment by tjsuominen** [comment]
Shall we make feature requests / wishes to this single thread or write each one seperately?

**Comment by tommasoberlose** [comment]
> Shall we make feature requests / wishes to this single thread or write each one separately?

Yes please, open a new issue using the feature request template. Thanks

**Comment by tjsuominen** [comment]
Will do, thx!

**Comment by tommasoberlose** [comment]
> Show current music in media player (YouTube Music in this case) in widget.

Added in the latest release.

**Comment by BracesForImpact** [comment]
Thanks so much! On May 10, 2020 5:26 AM, Tommaso Berlose <notifications@github.com> wrote:

Show current music in media player (YouTube Music in this case) in widget.

Added in the latest release.

**Comment by tjsuominen** [comment]
Lovely!

Could this still be further enhanced to include:

- smallish album art image and
- beside the album art on the right
  <Album title>
  <Song playing>
  <Artist name>

So that the three lines above have equal height to the album art image shown.

I could make a mock-up of such if interested.

**Comment by tommasoberlose** [comment]
> Lovely!
> 
> Could this still be further enhanced to include:
> 
> * smallish album art image and
> * beside the album art on the right
> 
> So that the three lines above have equal height to the album art image shown.
> 
> I could make a mock-up of such if interested.

I think to keep that feature easy, without any images or the album. I'm sorry.

**Comment by tjsuominen** [comment]
Sure, no harm done, it's your app :)

It's making great progress!

Just thought the visual could have made good fit in there.
