### ISSUE TITLE
App name is shown as LIB

### ISSUE THREAD

**Issue by chrisonline** [tommasoberlose/another-widget#7]
![screenshot_20171101-195238](https://user-images.githubusercontent.com/2077218/32291924-bfc263ec-bf3e-11e7-9803-0afe043e26ff.png)

![screenshot_20171101-195222](https://user-images.githubusercontent.com/2077218/32291917-bbedb17c-bf3e-11e7-85bc-7332045a26f6.png)
On my Pixel 2 with Android 8.0 the app name is shown as LIB instead of Another Widget.

**Comment by tommasoberlose** [comment]
Hopefully fixed in version 2.0.1.
