### ISSUE TITLE
Add "Time Until" event

### ISSUE THREAD

**Issue by Apad121** [tommasoberlose/another-widget#70]
Hi there 

In version 1 of Another Widget, we used to have the excellent option to display the time until a certain calendar event. If this could be brought back, that would be excellent!

Thanks

**Comment by vedanshgarg** [comment]
I think it is already present in the current versioin as "Time left to event"

**Comment by Apad121** [comment]
![image](https://user-images.githubusercontent.com/64892030/81151527-fce5fd80-8f78-11ea-955e-54e88d3dbf2b.png)

In the Calendar settings, I can only see "Time LEFT in the event" and no longer the "Time UNTIL event"so in the past, it will tell me how many hours minutes I have left until the event.

**Comment by vedanshgarg** [comment]
"Time left in the event" should show you the time left, as shown in the screenshot below

<img width="375" alt="Screenshot 2020-05-06 at 1 42 53 PM" src="https://user-images.githubusercontent.com/40305225/81152504-a04a0900-8f9f-11ea-95ec-831d589dd9b8.png">

**Comment by tommasoberlose** [comment]
I've updated the setting label from "Time left in the event" to "Time left to the event".
I hope this way could be more explicable.

**Comment by Apad121** [comment]
Thanks for the replies!
However even when it is ticked it still doesn't work for me? It doesn't tell me how many minutes/hrs until the event. It just displays the event in a few hours and doesn't tell me the time until then.

Thanks!
