### ISSUE TITLE
[Bug] Widget does not update (or quite delay in updating) once meeting (or event) has ended.

### ISSUE THREAD

**Issue by vedanshgarg** [tommasoberlose/another-widget#71]
**Steps to reproduce:** Once the event has ended, it should show the day and date. But the widget still shows the event name. (Atleast for quite a while)

**Expected behaviour:** It should show the day and date.

**Device info:** Oneplus 6 , OOS 10.0 (Android 10)

**P.S. :** Even tried with battery optimisation for the app turned off.

**Comment by vedanshgarg** [comment]
![Screenshot_20200506-185806](https://user-images.githubusercontent.com/40305225/81182603-a1912b00-8fcb-11ea-9dc4-3ddcedfcbf3a.jpg)

**Comment by leoyinjou** [comment]
Same issue. Seems like widget doesn't refresh until i launch the app from app drawer. The weather part seems fine though. Just calendar/events.
OnePlus 7 Pro running Android 10 OxygenOS 10.0.5
