### ISSUE TITLE
Widget event

### ISSUE THREAD

**Issue by sequelae75** [tommasoberlose/another-widget#72]
Pressing the event on widget direct me to the calendar app, but not the right place. 
Pressing an event today got me to the week 1 December 1970.
OnePlus 6, newest beta.
![Screenshot_20200506-115603](https://user-images.githubusercontent.com/64898355/81165038-9a4d2b80-8f91-11ea-9689-69af7e842027.jpg)

**Comment by leoyinjou** [comment]
Perhaps something common with calendar/events issue: https://github.com/tommasoberlose/another-widget/issues/73#issuecomment-624975654
