### ISSUE TITLE
Tap on Event opens Event Details fails on all day events

### ISSUE THREAD

**Issue by LastInLine** [tommasoberlose/another-widget#73]
If you have all day events visible and you have Tap on Event set to open Event Details in Google Calendar as the default calendar app, tapping on the event returns a toast "Event not found".  Happens regardless of the calendar it's on.

This is on Pixel 4XL, latest beta of Another Widget, Nova Launcher.

**Comment by leoyinjou** [comment]
I'm not sure if it helps with dev, but i have a similar problem, even on most recent (beta?) update.
Creating new event, wait for Another Widget to refresh, then edit the same event to a new time, wait for AW to refresh again, then click on the event on AW will result in the toast "Event not found".
OnePlus 7 Pro, running Android 10

**Comment by LastInLine** [comment]
This appears to be fixed in 2.0.9 (92)
