### ISSUE TITLE
Weather Icon is missed

### ISSUE THREAD

**Issue by Kayserslot** [tommasoberlose/another-widget#75]
Hi, since last update I'm not able to achieve  that weather symbol appears in the widget..... Just only a white dot shows in the place where the weather picture should appear (sun, clouds, etc...)..... I attach you screenshots.... 
![Screenshot_20200506-164234](https://user-images.githubusercontent.com/64912284/81191871-ce3c4700-8fb9-11ea-8ac3-b122e7d9a76e.jpg)
![Screenshot_20200506-165053](https://user-images.githubusercontent.com/64912284/81191873-cf6d7400-8fb9-11ea-87d8-45d53c4578eb.jpg)

**Comment by Moutony** [comment]
It is an actual cloud icon...

**Comment by Kayserslot** [comment]
No, because weather is sunny and it's always the same icon.... Being at night also....

**Comment by tommasoberlose** [comment]
I think you could refer to #57
