### ISSUE TITLE
Usage of storage - enormous

### ISSUE THREAD

**Issue by zayebystymis** [tommasoberlose/another-widget#76]
![Screenshot_20200507-111421](https://user-images.githubusercontent.com/64842474/81276972-0abc8100-9054-11ea-83ec-234606a97752.png)
What's going on 155GB of data needed for widget?

**Comment by tommasoberlose** [comment]
Wow, that's odd. I have just 3.5MB occupied by the app on my device.
After the data cleared up is the amount rising again?

**Comment by zayebystymis** [comment]
No, for now it's just 299kb, so it's completely fine. Maybe it's related with failing of retrieving weather data.

**Comment by tommasoberlose** [comment]
I think that could be related to the bitmaps generated from the widget.
I save only the settings preferences and future events (I remove the old ones every time that the widget updates).
I'll close the issue but let me know if the problem pops up again.
