### ISSUE TITLE
Widget size shrinks - issue

### ISSUE THREAD

**Issue by sairgon** [tommasoberlose/another-widget#79]
Widget text size decreases after playing more than an hour in pubg (opening pubg and exiting doesn't have an issue). Gotta refresh the widget for it to come back to normal.
Edit: this happens when events are displayed.
Also, running YouTube produces the same issue.

**Comment by tommasoberlose** [comment]
I will look into it.

**Comment by tolrm** [comment]
Happens to me also when displaying Custom Notes
