### ISSUE TITLE
Pressing Weather occasionally brings up Google

### ISSUE THREAD

**Issue by tolrm** [tommasoberlose/another-widget#80]
When pressing Weather in the widget occasionally the Google Discover window pops up instead of Google Weather. This occurs especially if shortly before pressing the widget Google Discover has been active.

**Comment by tolrm** [comment]
Still happens on the latest beta from yesterday. More info: Launcher is OnePlus Launcher. When the Google icon from the search bar is pressed and put in the background - not closed, pressing the weather widget reopens the Google page.

**Comment by tolrm** [comment]
same with build 79 but less frequent. It seems to happen most if I press the Google logo from the search bar on the homescreen and then select an item in Updates that brings me to an external webpage. Going back to the home screen and then subsequently pressing the weather widget goes back to this external webpage

**Comment by tolrm** [comment]
with 2.0.6 and 2.0.7 I have not been able to reproduce anymore, so suggest to close.

**Comment by tommasoberlose** [comment]
> with 2.0.6 and 2.0.7 I have not been able to reproduce anymore, so suggest to close.

Perfect!

**Comment by tolrm** [comment]
Re-occur with 2.0.8 (89) now consistently. If I press the Google logo which brings up discover, or if I type in the Search bar and then swipe up to go to the home screen thus putting Google in the background, then when pressing the weather part of the widget brings up the Google window.
My work-around is to use back a number of times to go to the home screen.
Note that I am using swipe up and swipe left/right gestures. My nav bar at the bottom is hidden...

**Comment by tolrm** [comment]
Strangely, when changing from FHD to QHD resolution, the problem disappears...
Not sure why there would be a dependency, though...

**Comment by tolrm** [comment]
With 2.0.9 (91) the bringing up of the Google window is now consistent after pressing the weather image in the widget across FHD to QHD resolutions.
My work-around still works...

**Comment by tommasoberlose** [comment]
Hey, I tried to replicate the issue on my device but I can't access Google right now, because the Google app crashes on my OnePlus 5.
Although there isn't a clear way to open the Google Weather widget from other applications, I use an undocumented API that opens an internal Activity of the app Google, so I think that that is causing the misbehavior that you're experiencing.

**Comment by tolrm** [comment]
Yes, that may be it. Google at a glance widget and also when I put the Google weather as a widget on the home screen do work correctly, but I do not know what API calls they use...
I further read that to enable Google at a glance in an alternative launcher (Rootless launcher), you would need to download a separate apk the Pixel bridge to get access to the Google feed. That apk is open source and may shed some light what API call to use...

**Comment by tommasoberlose** [comment]
I just checked every GitHub repository that supports the glance widget with the tap on the weather, and they all open the weather the same way I do.
I'll check again this issue when my device will be updated to Android 10, which hopefully will fix the problems with the Google App.

**Comment by tolrm** [comment]
Clear. Thanks for all your efforts looking into this!
