### ISSUE TITLE
Widget doesn't update

### ISSUE THREAD

**Issue by josh2112** [tommasoberlose/another-widget#82]
The widget on my home screen never updates. The only way I can force it to update is open and close the AnotherWidget app. I've deleted and re-added the widget, no difference. The widget is showing calendar and weather (clock disabled).

**Comment by tommasoberlose** [comment]
Please refer to #57

**Comment by josh2112** [comment]
I'm not sure why this was closed? #57 doesn't seem to have anything to do with this.  I have the OpenWeatherMapAPI key set up, I have location turned on for the app, and it works fine.

The problem is _neither the next calendar event nor the weather update_ unless I open the AnotherWidget app.

**Comment by tommasoberlose** [comment]
I've just released the v2.0.5 in production that fixed the updates problems.
