### ISSUE TITLE
Add simple line of text

### ISSUE THREAD

**Issue by tolrm** [tommasoberlose/another-widget#86]
At the moment I use another widget to display a simple line of text, e.g. owner's name and/or a quote. It would be convenient to have this included in a single widget. Like the other fields it should be possible to set font and size and colour if the text and maybe some formatting.
The line of text could be positioned above the time or below. (Another thought: use the tabs to order what information is on line 1, 2 etc. For example some like a line of text, then the date. Others the time, then date and then the line of text)

**Comment by tommasoberlose** [comment]
Added in the latest release.

**Comment by tolrm** [comment]
Hi Tommas, thanks for adding this. In what version is it implemented? I got 2.0.6 installed and I don't see it. Maybe I am overlooking something... I do see the Glance tab that allows Song playing and the display of alarms...

**Comment by tommasoberlose** [comment]
v2.0.7 inside the Glance section

**Comment by tolrm** [comment]
Installed 2.0.7 and indeed it is available as custom notes that get displayed in the second text line.
Is there a reason why the font size is limited to 28 pt? The current widget that I use Simple Text Widget does not have that limit and thus allows me to spread the text across the width.

**Comment by tommasoberlose** [comment]
I'll think about it

**Comment by tolrm** [comment]
Thanks, I see it is implemented in 2.0.8. I am trying to recreate below screenshot with a single widget... 

Using your widget, setting the textline at 40pt is still too small. I notice that clock at 26pt is larger than the text line at 40pt as per second screenshot

![Screenshot_20200511-105426](https://user-images.githubusercontent.com/53617851/81543074-e4f5eb80-9375-11ea-9409-201e453039b8.jpg)


![Screenshot_20200511-104756](https://user-images.githubusercontent.com/53617851/81542562-233edb00-9375-11ea-8009-662320f1082d.jpg)

**Comment by tommasoberlose** [comment]
I've updated the text size ranges.

**Comment by tolrm** [comment]
Thanks!
