### ISSUE TITLE
Show events at least 24 hours is missing

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#88]
The option Show events at least 24 hours is missing in the lastest app version.
I don't know if it is a coding error or on purpose, but I need this option: I need to know what event I do have tomorrow. 
The new longest period is 12 hours and it is too short for me.
My events are in the afternoon and I need to prepare them the day before...12 hours before is in the middle of the night!

 - Device: Xiaomi Redmi Note 7
 - OS Version: Android 9
 - App Version: 2.0.6 (81)

**Comment by tommasoberlose** [comment]
Fixed

**Comment by Moutony** [comment]
Ok thanks, i'll wait for the new update soon
