### ISSUE TITLE
Whether update problem

### ISSUE THREAD

**Issue by manishahlawat7** [tommasoberlose/another-widget#91]
**Describe the bug**
Always have to open app for whether update, its not happen it self

**Expected behavior**
Whether should be update it self, 

**Smartphone (please complete the following information):**
 - Device: [e.g. vivo v9]
 - OS Version: [e.g. Android 9.0]
 - App Version v2.0.6 (81)

**Comment by tolrm** [comment]
My resolution on OnePlus 8 Pro with Android 10 is to keep the app running in the background through locking in the Recents list and also to set Android to not optimize for battery usage.

**Comment by manishahlawat7** [comment]
I m also doing the same, but actual temperature is 30 degree C and app is
showing 25 degree C.

**Comment by tolrm** [comment]
Do you have the location set to a fixed location or depending on GPS location? I have the latter and it updates with the 1 hr frequency that I have set.

**Comment by manishahlawat7** [comment]
I set it on GPS Location, and on 30 minutes interwell.
But not updating the same.

**Comment by tommasoberlose** [comment]
Please refer to #57
