### ISSUE TITLE
Clock: AM or PM not visible

### ISSUE THREAD

**Issue by AdjeP07** [tommasoberlose/another-widget#92]
**Describe the bug**
After selecting 'visible' in menu item 'AM/PM indicator' clock is not showing any change, and no AM or PM indicator.

**To Reproduce**
1. Go to 'Clock'
2. Click on 'Show AM/PM indicator'
3. Select 'visible'
4. Notice no clock chance in preview.
5. Try also - without result - to refresh widget by selecting two horizontal lines upper right corner.
6. First choice there is 'Refresh widget'

**Expected behavior**
After selecting menu item 'showing AM/PM indicator' by user I expect the 24 hr clock to change to 12 hr clock with AM or PM indication.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - OS Version: Android 10
 - App Version: v2.0.7 (84)

**Comment by tolrm** [comment]
On my OnePlus 8 Pro this will only appear if under Android Settings, date/time setting has "Use 24 hour" format de-selected.

**Comment by tommasoberlose** [comment]
The clock hour format is based on your system settings.
