### ISSUE TITLE
Synced iCal (.ics) calendars are not displayed in the widget since v2 update

### ISSUE THREAD

**Issue by charlie969** [tommasoberlose/another-widget#94]
I have a number of external iCal calendars (such as my work Outlook calendar) synced with Google Calendar. These show in the "Other Calendars" section of Google Calendar online, and appear in the Google Calendar app. However, they are not recognized by Another Widget since the v2 update.

**Comment by tommasoberlose** [comment]
I can only control the events that are saved on the device calendar provider. I think that that could be a Google Calendar limit.

**Comment by charlie969** [comment]
That's strange, it worked under the previous version of Another Widget...

**Comment by charlie969** [comment]
The calendar is shown under the "Filter events" list in Another Widget, it's just that the events don't seem to be recognized.

**Comment by tommasoberlose** [comment]
Did you try to toggle the calendar filter?

**Comment by charlie969** [comment]
Yes, I've tried ticking/unticking and refreshing the widget - no change, despite the fact I have several events today and the widget is set to show events up to 6 hours ahead.

**Comment by tommasoberlose** [comment]
I made a few tests and I was able to view the imported calendar events after I synced the calendar inside the Google Calendars settings. Can you check if the outlook calendar is correctly synced by Calendar?

**Comment by charlie969** [comment]
Yes, the calendar is synced and shown in the Google Calendar app - including event name, location, description, etc. The "going" status isn't shown though, I don't know if that could be affecting it?

**Comment by tommasoberlose** [comment]
> Yes, the calendar is synced and shown in the Google Calendar app - including event name, location, description, etc. The "going" status isn't shown though, I don't know if that could be affecting it?

I only check if the "going" status is DECLINED.
I actually don't know how to replicate the error, I already tried to sync with my google account an external .ics calendar and it showed up.

**Comment by charlie969** [comment]
This is bizarre - I just created a new "test" calendar within Outlook 365 and imported the ics link to Google Calendar, and it shows up fine in Another Widget. For some reason, though, my default calendar still doesn't show. I'm stumped!

**Comment by LastInLine** [comment]
@charlie969 I don't know if this is feasible or easy to do, but what if you remove the synced calendar from Google Calendar then re-add it?
