### ISSUE TITLE
"Use geolocation" not working

### ISSUE THREAD

**Issue by jutgreen** [tommasoberlose/another-widget#96]
**Describe the bug**
When attempting to "Use geolocation" for weather I am not receiving any feedback from tapping the option. Since I believed it was not updating the location as expected, I was able to verify by changing to a different city/state manually, then selecting "Use geolocation" again and confirmed nothing happens. 

**To Reproduce**
1. Go to "Weather'
2. Tap on 'Location'
3. Tap on 'Use geolocation'
4. No feedback received

**Expected behavior**
Some type of confirmation of the choice to the use geolocation service as well as it automatically updating location (which is is currently not doing for me).

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS Version: Android 10 - May 5, 2020 Security Patch Level
 - App Version: v2.0.8 (87) 
     - Note: also noticed in previous version

**Comment by tommasoberlose** [comment]
Did you grant the background location permission to the app?

**Comment by tommasoberlose** [comment]
And please refer to #57

**Comment by jutgreen** [comment]
@tommasoberlose I granted all permissions that were requested during setup, location permission was not prompted for access. I manually enabled location permissions this morning (via Android Settings > Permissions) and can confirm geolocation is working as expected now.

**Comment by tommasoberlose** [comment]
Perfect, thank you for the feedback!
