### ISSUE TITLE
FR: Random Quote

### ISSUE THREAD

**Issue by tjsuominen** [tommasoberlose/another-widget#98]
Would love to have on the "At Glance" part a function for **Random Quote** as for motivation:

- appears only if no meeting, music, playing, alarm in place
- ONLY for short quotes
- one sample location: https://wisdomquotes.com/short-quotes/ ;they are brilliant

If no such fetch feature from web / database:
Alternative1: ability for user defined text file (read random lines)
Alternative2: utilization of "Custom notes" WITH ability to a multi-line (CR)

![quote](https://user-images.githubusercontent.com/7660277/81563108-83964280-939e-11ea-88f5-6afb5a4d5b81.png)

Comments, feedback?

**Comment by tommasoberlose** [comment]
I searched for a few short-quotes API services but I didn't find out anyone with documentation.
I've updated the custom notes UI to show two lines in the widget.

**Comment by tjsuominen** [comment]
Excellent alternate, thx!
