### ISSUE TITLE
Problem Loading Widget (Version 2.0.7, 84)

### ISSUE THREAD

**Issue by wees** [tommasoberlose/another-widget#99]
Widget displays as box with text "Problem Loading Widget"

I've tried disabling all extras like weather, calendar, etc, but the widget never displays.
I've tried removing and re-adding the widget, restarting the widget in the settings panel, and restarting my phone.

If there is a way to display logs or any other debug messaging, please let me know and I'll provide those logs.

 - Device: Google Pixel 2XL, 
 - OS Version: Android 10
 - App Version (that you can find inside the advanced settings) [e.g. v2.0.5 (71)]

**Comment by tyj144** [comment]
Running into the same issue, v2.0.7 (84) running on Pixel 2 and Android 10.

Tried enabling the permissions, reinstalling the widget, and putting in OpenWeather API key. Putting in the API key helped temporarily, but it's back to "Problem loading widget" now.

**Comment by SmexxyMoose** [comment]
I'm getting the same thing. Latest version on Android 10e. Reinstalled, and tried a new API key but nothing has worked.

**Comment by tommasoberlose** [comment]
Is the problem still present in the latest release?

**Comment by SmexxyMoose** [comment]
> Is the problem still present in the latest release?

Thankfully it is resolved and now works wonderfully. Thank you!
